cloudevents/spec

CONTRIBUTING.md
spec.md

Signed-off-by: Austen Collins <austen@serverless.com>

initial spec

---

.travis.yml
Makefile
spec.md
tools/verify-links.sh

Any good spec needs to use RFC2119 keywords, so this starts us down that path
by added a ref to it. Doesn't introduce any uses of the keywords yet.
Added an href checker tool so that we can make sure we don't have any
bad hrefs in our docs.
Also added a travis hook so we run the verification script as our build.

add ref to RFC2119 and href checker

---

GOVERNANCE.md
README.md

Add initial pass at our governance model

---

spec.md

There were just a few spot in the spec where the formatting wasn't
consistent (they didn't wrap at 80 cols). Just syntax clean-up.

Fix formatting in spec to wrap at 80 cols

---

spec.md

During the last call we agreed to open up issues for the "Notes" in the spec
for the backlog of context properties. Now that those action items are done
we can remove those bits of text from the spec.
Note, some of the backlog context attributes might be added back in as
"agreed to" attibutes, but we'll decide that while resolving the corresponding
issue.

Remove Notes/Attribute-backlog from spec now that we have issues for them

---

README.md
roadmap.md
spec.md

Adds a basic overview of the effort and an initial road map.
Signed-off-by: Austen Collins <austenATserverless.com>

Add readme description and initial road map

---

spec.md

Rename attributes 'resource*' to 'source*' 

---

CONTRIBUTING.md

Per our call last week people wanted a bit more guidance about the
DCO checker and what their git commits should look like w.r.t. signing.

Add some more git help text

---

spec.md

Reworded the description of the term event to remove ambiguity around words message and notification
Fixes #6 
Signed-off-by: Suhas Chatekar <suhas.chatekar@gmail.com>

Issue 6 - Definition of Event in the terminology section is confusing

---

spec.md

My editor keeps automatically stripping whitespace from the ends of lines. I don't think the linter for this repo cares one way or the other, but it seems unfortunate for 3 lines to end with a space while the rest don't. 
Normally I would just include this in some more relevant actual PR but in the interests of not confusing things, making it its own change. 
Signed-off-by: Ben Hartshorne <ben@honeycomb.io>

removing trailing whitespace from the end of lines

---

CONTRIBUTING.md
references.md
spec.md

- spelling mistake
- wrap at 80 chars
- remove trailing spaces
- put json properties on their own lines

Fix some syntax issues

---

spec.md

https://github.com/cloudevents/spec/issues/83
The definition of "occurrence" is unnecessarily narrowing the scope of what an occurrence may be, especially by calling out specific technologies/protocols.

Definition of "Occurrence" #83

---

spec.md

Collapsed the 12 scenarios from the email to 4 and added clarifying discussion

Usage Scenarios

---

about/contributors.md

This list acknowledges people who contributed to the draft spec before it was on github,
and also allows us to include people who make substantive contributions in other forums,
such as the Serverless WG meetings where participation is tracked outside of github.
Also, it is very helpful to have easy reference to the projects that contributors are working on
where they use (or hope to use) CloudEvents.  
Closes #42

Contributor list

---

spec.md

In an attempt to get to a MVP for the spec, I'm proposing to collapse source-related attributes (source* & namespace) down to a single URI whose format/encoding is event producer defined.
Future PRs can suggest that we split out certain bits of data from this URI (e.g. for performance, optimization or other reasons), but then those discussions will be more focused on just the specific need being addressed, so hopefully will be easier to reach a consensus.

Source as a URI

---

Makefile
extensions.md
spec.md

There is a strong desire by the WG to keep the list of attributes we include in the specification down to the minimum necessary to achieve our goals. However, there have been some attributes proposed that seem to be popular in some usecases, but just not enough usecases to cross the threshold of being included in the spec as formal attributes. We've talked about possibly having a spot to put those attributes so they can be used as extensions - then at least there's the possibility of some amount of interop around them even if they have no official standing from our WG.
To that end, this PR proposes a starting doc to host some extensions that people can use.

First pass at an 'extension attributes' doc

---

serialization.md
spec.md

Closes #17 
I would actually prefer if we just move this into the main spec itself since its so small, but for now I started out with it being in a separate doc with the assumption that we can decide on whether we want to merge it later.

add json serialization

---

spec.md

Closes: https://github.com/cloudevents/spec/issues/85
Eliminating overlap with occurrence definition. Also taking out the delineation from message since that's not a defining characteristic.

Definition "Event" #85

---

spec.md

This section seems unnecessary and old...
- it talks about our scope, but I think we cover that in our "Overview" and "Design Goals" section
- it has a list of TODOs, which we've already done most of, and for the ones we're still working on they would be better tracked via Github issues (and they are)

Remove the Status section of the spec

---

serialization.md
spec.md

Add reverse-DNS namespacing to `event-type`.  This commit has been spliced off of https://github.com/cloudevents/spec/pull/129.
I agree that removing `namespace` from the spec was a step in the right direction because it was ambiguous what is being namespaced. This change proposes that event types are themselves namespaced. This can be important for any proxy or action that chooses to group related streams of events. As I've said before, there's a very big difference between "document.create" events when you're referring to a Word document or a Mongo document.
Updated seralization.md, including removing the "namespace" parameters that were already removed from spec.md.
A GitHub pull request event from github.com
```json
{
"source-authority": "github.com",
"source-path": …
```

Add namespacing to event-type

---

roadmap.md

**Note:** This is a clone of #156 that was created to get around DCO issues.
This PR adds deliverables to 0.1:
Include a specification for mapping the CloudEvents specification to HTTP.
Include a specification for mapping the CloudEvents specification to JSON.
Define a type system for CloudEvents values.
This PR also does minor clean-ups (that don't intend to change our intentions).
Signed-off-by: Austen Collins austen@serverless.com

Roadmap - Add deliverables to 0.1

---

spec.md

We don't need the TBD since each mapping/serialization doc we produce
should state how extensions should appear. E.g. https://github.com/cloudevents/spec/pull/148
Closes: #125

Remove "TBD" comment about extensions

---

spec.md

URI-reference is a URI or relative-ref. This
now makes our existing examples meet the spec
as defined. Notably, this allows schemaless URIs.
Per 4/19 meeting, this will be merged as 0.1 if
it has sufficient approvals by then.
Signed-off-by: Thomas Bouldin <inlined@google.com>

Define URIs to follow the URI-reference rule.

---

http-transport-binding.md
json-format.md
spec.md

Also added a "Status" section to be consistent across all 3 docs.
This should address @inline's concern about people thinking anything
is set in stone because now it says its a 'working draft'.
One thing we need to decide, later, is whether to have section numbers or not, we not consistent right now.

Add "Version 0.1" to some md files in prep for release

---

spec.md

Closes: https://github.com/cloudevents/spec/issues/86
Clarification that context information describes the circumstances of the event and not the occurrence per-se.

Definition "Context" #86

---

community/open-source.md
spec.md

As an open-source project, I'd like to add my [CloudEvents.NET](https://github.com/aliencube/CloudEvents.NET) as a .NET implementation.
In addition to this, I found a typo and fixed it.

Add CloudEvents.NET as a .NET implementation project

---

http-webhook.md

This PR complements https://github.com/cloudevents/spec/pull/148 
This specification is a *generic* specification that formalizes delivery of notifications over HTTP, generally known as "Web hooks". The HTTP transport binding for Cloud Events composes with this specification for one-way event delivery.
The specification defines that notifications are delivered by HTTP POST, should use a token-based authNZ scheme either carried in the Authorization header or the query string (whereby "token" can be a simple key), and strongly suggests implementation of a pre-flight handshake (similar to [W3C CORS](www.w3.org/TR/cors/)) that protects a sender from being abused as a distributed denial of service machine gun.
This specification would probably be best proposed to IETF, but here's a good place …

HTTP WebHook Specification

---

Makefile
README.md
nats-transport-binding.md

I'd like to propose a [NATS](https://nats.io) transport binding for CloudEvents, similar to the [HTTP](https://github.com/cloudevents/spec/pull/148) binding and proposed [MQTT](https://github.com/cloudevents/spec/pull/158) and [AMQP](https://github.com/cloudevents/spec/pull/157) bindings.  This PR borrows heavily from the MQTT proposal.
Signed-off-by: Colin Sullivan <colin@synadia.com>

NATS transport binding

---

README.md
spec.md

I found it a bit odd that the spec never included an example CloudEvent.
People would have to go to one of the other docs to actually see what
one looked like. For me, its sometimes easier to full understand something
when I can see a real example of what is being defined. Having people leave
our doc to see one felt odd so I just copied one from the JSON mapping spec.
While in there I noticed that our TOC wasn't consistent w.r.t. what we
included so I put all 1st and 2nd level headings in there (excluding the
ones before the TOC).
Also, the TOC included references to two docs w/o any explanation around
them - the usecases and example events from some popular eventing systems.
None of these are normative so they felt really odd to be in our spec's
TOC. However, since they are useful bits …

Add an example to the spec and clean-up a little

---

spec.md

There has been a good deal of confusion about the role of contentType and whether it designates the contentType of the event per-se or of the event's data attribute. This change clarifies that it is meant to designate the content type of the latter. The content type of the event encoding is defined by the respective event format.

Clarify contentType

---

extensions.md

I think this merits the initial statnce of being an extension
for a few reasons:
1. I want to adhere to the CNCF policy against kingmaking even
though I think the world is better off with one interoperable
tracing standard.
2. Nothing in the trace state should have an effect on
application logic.
3. I like exercising our thoughts on extensions.

Add extension for Distributed Tracing spec.

---

.gitignore

It's very helpful to use IDEs that let us visualize the rendered markdown. It would be more helpful to not worry about local project files getting added to commits.

Add popular IDEs to .gitignore

---

README.md

@clemensv I'm not sure if it was intentional or not to not add the links to AMQP specs on the front page.

Add links to AMQP transport and event formats

---

extensions.md
extensions/distributed-tracing.md

* Extends extensions.md to clarify that RFC 2119 keywords
are only for those who implement an extension.
* Notes our resolved rules that each memory format defines
extensions' placement and each transport binding defines
a default placement which an extension may override.
* Refactor the contents now in extensions/distributed-tracing.md
as a first SWAG at a reusable template.

Factor Distributed Tracing extension into new doc.

---

roadmap.md

In the 2018-06-15 f2f, we agreed to holistically revisit the spec
to look for issues that may arise with our spec in practice.
As a first swag, I placed this in the 0.3 milestone since it
has security-related issues. I could also see putting this in
the 0.4 milestone since it finalizes serialization and protocol mappings.

Add practical constraints exercise to 0.3 roadmap.

---

community/open-source.md

This adds the cloudevents-python library and the CloudEvents.live debugger.
Signed-off-by: William Rudenmalm <me@whn.se>

Add cloudevents-python & CloudEvents.live to open-source

---

http-transport-binding.md

Mapping rules for HTTP headers, including stating that extensions can do their own thing. I also added a rule for all 'Map' typed attributes, which will catch whatever we call 'application-properties' once they land.
If this meets everyone's expectations, I will do the equivalent edits for the other protocols.
On prefixing, I am landing on keeping CE- for everything from CloudEvents (including extensions) for HTTP so that we don't get in the way of similar HTTP constructs as HTTP headers aren't structured. For MQTT and AMQP it's not going to hurt to align to the same convention even though they have richer structure.
#Signed-off-by: clemensv@microsoft.com

Mapping rules for attributes/headers

---

json-format.md
spec.md

This solves https://github.com/cloudevents/spec/issues/142
I added a sentence to the definition of schemaURL claiming that incompatible changes to the schema SHOULD result in a new schema version. Please let me know, if you are fine with this.

Removed eventTypeVersion

---

community/open-source.md

Signed-off-by: Sandro Martini <sandro.martini@gmail.com>

Add CloudEvent.js to open source resources

---

extensions.md
extensions/sampled-rate.md
spec.md

This pull request supercedes #76 and builds upon #242.
Per agreement at the f2f meeting 2018-06-15, this will be ratified
as an extension but not currently as part of the core spec. The
early inclusion of the spec and the ability for side-cars to impose
sampling early in the pipeline make it reasonable to start with
this as an extension.
I know the original author hoped to make this a core feature, though
there are two upsides:
1. Due to other decisions on 2018-06-15, this will have zero impact
on JSON encoding (but will in Proto and may in SDKs)
2. Extensions now get a whole document. This lets us pitch sampling
in more detail.
Necessary additional changes:
* Added `Integer` to our type system
* Added convention for how scalar extensions should be documented.
I'm not really excited about …

Add sampling extension.

---

primer.md

This paragraph should provide technical motivation for keeping the usage of extension attributes in check. For background information, see https://github.com/cloudevents/spec/issues/286
I expect that the following paragraph from https://github.com/cloudevents/spec/pull/277 will precede the paragraph I'm proposing, which provides a more conceptual motivation for limiting the usage:
```
Extension attributes to the CloudEvent specification are meant to
be additional metadata that needs to be included to help ensure proper
routing and processing of the CloudEvent. Additional metadata for other
purposes, that is related to the event itself and not needed in the
transportation of the CloudEvent, should instead be placed within the proper
extensibility points of the event itself.
```
I do think …

Technical motivation for keeping extension attributes minimal

---

GOVERNANCE.md

this is based on what I've observed in TOC votes and seems to work well in practice (though I've only followed a few votes)

async voting process 

---

spec.md

Signed-off-by: cathyhongzhang <cathy.h.zhang@huawei.com>

Add clarification on including additional context attributes

---

primer.md

de-facto standards often emerge from the community
joining a consortia should not be necessary
Signed-off-by: Sarah Allen <sarahallen@google.com>

qualifying projects

---

GOVERNANCE.md
OWNERS
README.md
community/contributors.md
primer.md
roadmap.md
share/README.md

- Just writing down what we do/have today
- We're not a WG, we're a sandbox project so I tried
to remove all references to us being a WG (I left the refs to the
Serverless WG though)
- wrapped some stuff at 80 cols
- replaced some tabs with spaces, because tabs are evil

Minor tweaks to our governance docs

---

documented-extensions.md

First pass at trying to define our "bar" for new extensions.

Define our "bar" for new extensions

---

amqp-format.md
amqp-transport-binding.md
http-transport-binding.md
json-format.md
mqtt-transport-binding.md

Striking one of my homework AIs from the list, this provides an “escape hatch” in our event format and transport specs to allow attributes of extension specs to override the general serialization rules and metadata mappings.
This PR covers the JSON and AMQP event format specs and MQTT/AMQP/HTTP transports (NATS is not affected) and allows for diverging encoding rules defined by an extension _IF_ that extension defines encoding rules for all core formats.

Encoding exceptions

---

amqp-transport-binding.md
http-transport-binding.md
json-format.md
mqtt-transport-binding.md
nats-transport-binding.md
spec.json
spec.md

At least week's meeting I was asked to create PR as a follow-up to my oral comment on https://github.com/cloudevents/spec/pull/317
I appreciate the work done on that PR and the attempt to preserve case-sensitivity through an HTTP hop where the actors might perform case-folding for any reason, including semantically pointless aesthetics, due to HTTP being case-insensitive. That PR having to introduce complex rules is an issue with the main spec, and not something the HTTP mapping ought to fix, IMO.
This PR puts a constraint on the attribute name character set, only allowing lower-case letters and digits, with a leading lower-case letter. I am also including the rationale in the spec. 
In effect, we are not taking a stance on case-sensitive or case-insensitive handling, but we rather …

Restricting character set for attribute names

---

spec.md

Signed-off-by: Fabio José <fabiojose@gmail.com>
PR related to issue [#332](https://github.com/cloudevents/spec/issues/332)
Closes: #332

Some suggestions in Example section

---

README.md
spec.md

Proposed changes to consistently name the concepts of event producer and event consumer to align with the existing definition of  the "source" attribute.

Word-smithing (event "producer" and "consumer")

---

amqp-format.md
documented-extensions.md
json-format.md
spec.json
spec.md

Following the discussion in https://github.com/cloudevents/spec/issues/332, we figured out that the spec actually meant to support URI-references all along. However, by defining the type as `URI`, it is easy to make a mistake and assume it is only a URI, not a URI-reference.
This mistake was also made in the JSON Schema.
This PR therefore does three things:
* Rename the type to `URI-reference`, in order to make it easier to grasp for others in the future
* Fix the JSON Schema
* Add an example for a relative URI
The main changes are in `spec.md` and `spec.json`.

Rename URI to URI-reference, fix JSON Schema

---

Makefile
cloudevent.proto
protobuf-format.md

This PR is meant for the spec as it is currently written, where the
extensions is an explicit bag. The focus of this PR is on the protobuf
format itself, not on the extensions proposal.
Signed-off-by: Spencer Fang <spencerfang@google.com>

Add protobuf format

---

amqp-transport-binding.md
community/contributors.md
http-transport-binding.md
json-format.md
mqtt-transport-binding.md
nats-transport-binding.md
roadmap.md
spec.json
spec.md

Simplified/Reduced context property names.
Closes #323

Simplified/Reduced context property names.

---

json-format.md
protobuf-format.md

This PR addresses a concern [raised](https://github.com/cloudevents/spec/pull/295#issuecomment-435609246) by @JemDay that the [proto spec](https://github.com/cloudevents/spec/blob/master/protobuf-format.md) didn't specify which media type should be used in the envelopes for messages using the proto spec. 
This follows the convention of the json spec and specifies the media type of `application/cloudevents+proto`.

Specify the media type for proto representations

---

json-format.md
primer.md
spec.md

The Primer is a good location to document some of our design decisions
without cluttering the spec with non-normative text. This is my first pass
at some of the reasons why we're serializing extensions as top-level
properties in JSON.
Note, as you review this please focus on whether the text accurately
reflects the reasons why we ended up with our current design. This PR
should not be used to question whether it was a good or bad decision.
If you want to question the decision itself then a new issue (or PR) is the
best place to do that - I'm just trying to document history.

Add some rationale for our extensions decision

---

primer.md
spec.md

Just because @ac360 wanted to see it.

Add clarity text and an example of versioning eventTypes

---

README.md
SDK.md

This spec is the first step towards nicely-shaped CloudEvents SDK spec.

CloudEvents SDK spec proposal

---

spec.md

"32 bit integer" is under-specified, there are multiple ways to encode an
integer in 32 bits with different ranges (signed, unsigned, twos-complement,
ones-complement etc.)
Proposed new wording: "signed 32-bit twos-complement"

Specify range of Integer type exactly

---

primer.md

Follow up to the discussions in #330 and #282 : Since it seems to be a frequently asked question, we should somewhere in the spec write down how to handle multiple messages.
I think the `primer.md` is the place that fits best. I'm not sure if the Design Goal section is a perfect fit, but I didn't find a better place.

Transports are responsible for batching messages

---

spec.md

In https://github.com/cloudevents/spec/commit/3248e31cabace2c8d8d8da46a033923d598c1bfb `Integer` was added as an allowed shape of the variant type `Any`, but the modification was left out of the later description of the variant type, which also lists the allowed shapes. Added `Integer` to the list and made it the same textual style as in the type list. So no normative changes.
Another possibility is to just change the text describing the variant type to refer to the type list instead of repeating the list.

Add Integer as allowed for Any in description of variant type

---

spec.md

Minor cosmetic edit: This formats `data` consistently with the paragraph above in the contenttype section.

Minor: Format data consistently with the paragraph above

---

spec.md

After renaming of `eventtype` there is a dangling reference to the old name
No normative changes.

Fix eventtype -> type reference in it's description

---

http-transport-binding.md
json-format.md

In the discussion from last week about https://github.com/cloudevents/spec/pull/360 we agreed that a batching option for the HTTP Transport Binding is useful. This is an attempt to introduce it.
During the call, @clemensv suggested to build the batching into the structured mode. I couldn't figure out how to do this generically for any event format. Instead, I did it for the JSON format only.
I also did not include the batching mode as one of the modes the receiver SHOULD support. Take a Function as a Service: Usually, each event should be processed in on an own instance of a function. This is trivial to implement when a HTTP Request always contains a single event. A batch doesn't map nicely onto the core FaaS abstractions.
The HTTP Content-Type is a bit tricky - we want that the receiver …

HTTP Transport Binding for batching JSON

---

protobuf-format.md
spec.json
spec.md

Closes #384
In https://github.com/cloudevents/spec/pull/169 it was decided that inside the specification, we only use `URI-reference`. (From reading the PR, it is not clear to me whether it was intended to change both `schemaurl` and `source`, or only `source`, but the PR effectively changed both).
In https://github.com/cloudevents/spec/pull/338 I renamed the shorthand `URI` to `URI-reference`, because it was easy to wrongly assume only URIs are supported, but not URI references.
I missed changing the `schemaurl` type.
When `schemaurl` was introduced to `spec.json`, that was mixed up as well.
Related, the `protobuf-format.md` type mapping wasn't consistent with the type naming in `spec.md` (I think both PRs ran concurrently), which I'm fixing as well.
---
There is probably a discussion to …

Consistency: schemaurl uses URI-reference, protobuf uses URI-reference

---

extensions/distributed-tracing.md
extensions/sampled-rate.md
extensions/sequence.md

#321 made attribute names lower case, but did not apply the new rule to extensions.
This PR cleans that up.

Extensions follow attribute naming scheme introduced in #321

---

spec.md

Closes #401 
Also added changes the title of the sub-section to make it clear we're talking about context attributes

Move "extension attributes" section down to end of context attributes

---

spec.md

Signed-off-by: Day, Jem <jday@paypal.com>

Privacy & Security

---

proprietary-specs.md

As we discussed in the Apache RocketMQ binding [PR](https://github.com/cloudevents/spec/pull/352) and followed with the voting result in the [PR](https://github.com/cloudevents/spec/pull/380), we proposed this PR.

Add Apache RocketMQ proprietary transport binding with cloudevents

---

spec.md

Based on last week's debate on a missing context qualifier and the Knative project apparently now running into similar implementation issues for generic dispatch infra that we're having in Azure Event Grid, I am herewith reintroducing "subject" for consideration.
The (extensive) argument for the "subject" field is in the (closed) issue #112. I'm also talking through it in the audio  track attached to this presentation https://github.com/cloudevents/spec/blob/master/share/2018-03-22-TopicsAndSubjects.pptx and the presentation itself illustrates the topic ("source") and subject split.

Introducing "subject"

---

extensions/dataref.md
spec.md

This resulted mostly out of the discussion around https://github.com/cloudevents/spec/pull/364 but is also related to https://github.com/cloudevents/spec/issues/373
The Claim Check Pattern is used for different purposes, including large payload size and security concerns.
This is on purpose "hand-wavy" around the actual retrieval of the payload.
The advantage is that in this way, any auth and storage can be used, e.g. the blob storage of a cloud provider and the protection by their auth mechanisms.
The downside is that it is hard for a middleware or a SDK to retrieve the payload. A non-protected HTTP(S) endpoint would be simpler.
@JemDay I would appreciate it if you could give this a read :)

Add dataref attribute and describe Claim Check Pattern

---

primer.md

Adjust examples to include AWS CloudWatch events, our de facto central Event format, and remove valid-but-not-terribly-relevant SNS & Kinesis examples.
Signed-off-by: Tim Bray <timbray@amazon.com>

Adjust examples 

---

amqp-transport-binding.md
http-transport-binding.md
json-format.md
mqtt-transport-binding.md
nats-transport-binding.md
protobuf-format.md
roadmap.md
spec.md

This change bumps the version used in master to `0.3-wip` of the spec.
This becomes very clear (and confusing) when you are reading the examples of features are are only in `0.3-wip`, like Batch support.
Signed-off-by: Scott Nichols <nicholss@google.com>

Master represents the future version of the spec, use the future version in the text.

---

documented-extensions.md
extensions/partitioning.md

Closes #209.
This adds an eventKey field to the spec, for the purposes of establishing a causal relationship between events.
It would be worth discussing and getting feedback from multiple sources on the type of this field. Originally, I was going to make it `Object`, but if it's an object, it may need additional information around it such as a content type.
Instead I've made it `String` for simplicity, this works well with existing implementations such as AWS Kinesis and Azure Event Hubs, but may present an issue for Kafka which treats its keys as binary, and provides out of the box support for example for 64 bit long encoding and double precision floating point encoding. That said, it's not impossible for Kafka to support this, it just means any automated support for events in Kafka …

Proposal for an event key field as an extension

---

spec.md

This is for issue #331
Signed-off-by: Alan Conway <aconway@redhat.com>

Clarify scope of eventID's uniqueness

---

spec.md

I added some definitions to the terminology section of the spec. I know there might be some discussion, especially regarding the producer. I need these terms to better propose rules of when and how the event context can be changed.

Terminology additions for Source, Consumer, Producer and Intermediary

---

primer.md

Add some additional design points for ID

---

amqp-format.md
amqp-transport-binding.md
http-transport-binding.md
mqtt-transport-binding.md
spec.md

This amends the type system section such that any type can be represented as a runtime or transport or encoding sees it fit, but that all implementations MUST support a canonical string representation. 
Fixes: #396
Fixes: #413

Type system changes // canonical string representation

---

spec.md

This is an alternate proposal for #395 and #364 which states a simple 64 KByte "should" wire-size limit for publishers and for consumers along with guidance to refer to large data items instead of including them,

Size Constraints

---

primer.md

Since not all event producers will generate CloudEvents natively, it might
be good to provide some guidance around how the CE attributes should be
populated when the CE producer isn't the event producer.

Add some guidance on how to construct CloudEvents

---

spec.md

Also removed the redundancy between the two sentences applying to `Any`.
Signed-off-by: Gunnar Morling <gunnar.morling@googlemail.com>
Hey @duglin, as requested here's a new PR with the change around `Any`.

#436 Clarifying that Any can take the shape of any other type

---

README.md

It was noticed that we were missing the protobuf spec - while in there I alphabetized things

Fix README table - missing protobuf and reorder

---

primer.md

I have an open AI that has nagged me each week for the better part of the last decade to add some more content to the primer. I want to be a little careful with doing that because we've got a lot of authors on this document already, so I'll be doing smaller chunks. 
This PR adds an architecture summary of how the specs relate, which I don't think we have yet. There's a parallel PR (#389) for the SDK doc that is worded somewhat differently and presents how that same layering ought to be reflected in the SDK class/object/structure model.

Primer edits - Architecture section 

---

primer.md

Extend the non-goals section to clarify what is simply out of scope and
what is in scope but the WG thinks is a bad idea. The latter category
deserves fuller explanations for newcomers.

Add non-goals for routing information.

---

primer.md
spec.md

Forwarding OPTIONAL attributes 

---

primer.md

Briefly detail the importance and challenges of persistence and the measured approach to addressing it and its requirements within the CloudEvents specification.
Closes #143
Closes #276
Closes #378
Signed-off-by: Erik Erikson <erik.erikson@gmail.com>

Address Persistence in Primer

---

GOVERNANCE.md

It's been mentioned that we have no provision for a leave-of-absence
(e.g. vacations) w.r.t. voting rights. Luckily, we don't vote very often
and they're usually land-slides so I don't think it's impacted anything, but
we should probably have some kind of official allowance for it.
See what ya'll think...

Allow for a LOA w.r.t. voting rights

---

amqp-transport-binding.md
extensions/dataref.md
http-transport-binding.md
json-format.md
kafka-transport-binding.md
mqtt-transport-binding.md
nats-transport-binding.md
primer.md
spec.md

This might address #482 #471 #470 

tweak how we talk about data and datacontentencoding

---

primer.md
spec.md

I can't think of a good reason why URI-references should be allowed to
be blank since that seems about as useful as the property not being
there at all.
Closes #473

Tweak URI-references and be smart with Strings

---

amqp-format.md
avro-format.md
json-format.md
protobuf-format.md
spec.md

Some cleanup in our event formats:
* Removed `Map`
* Added `URI`
All event formats reference back to the `Type System` (e.g. https://github.com/cloudevents/spec/blob/master/json-format.md#22-type-system-mapping also includes a relative link).
Therefore I think it is worth adding a heading for it that can be linked back to.

Cleanup: Map and add URI in formats; re-add "Type System" heading

---

adapters/aws-s3.md
adapters/gitlab.md
json-format.md
spec.json
spec.md

remove dataencoding and intro data_base64 in JSON 

---

http-transport-binding.md

Update based on feedback from #456 
1. Define Context-Encoding header mapping based on `datacontentencoding`
2. More clearly define percent-encoding (and particularly percent-decoding) rules.

Clarifications on the HTTP transport binding

---

spec.md

Minor follow-up to #492 - I noticed this when checking the closure of #481 .
All attributes in this section are truly optional (again), no attribute is required under some conditions anymore 👍 
We can simplify the header again.

Only OPTIONAL attributes (conditional not needed)

---

avro-format.md
spec.avsc

It looks like we didn't update the AVRO format to actually include a place to store `data` when we graduated the payload from a special attribute to a header + payload model.

Update AVRO mappings to match current event schema and type system.

---

json-format.md
spec.md

Evan noticed we have more than one #data header so I tried to fix that.
Also, we still used a complex/map in an example.

Syntax fixes

---

amqp-format.md
amqp-transport-binding.md
avro-format.md
documented-extensions.md
extensions/distributed-tracing.md
http-transport-binding.md
json-format.md
mqtt-transport-binding.md
spec.md

Fixes #498 
This PR makes CE extensions follow the same rules as all other CE attributes. Meaning:
1 - they MUST be serialized with `ce-` prefixes in transports like binary-http
2 - they MAY have a secondary serialization, but they MUST still have the `ce-` prefixed one too.
3 - if they do, and the values differ, then the `ce-` version is the CE attribute. The other one, if picked-up by the middleware, is 'some other' metadata that it's passing along.
This means that a CE receiver no longer needs to look any place except in one location for ALL CloudEvents data. This also means that ALL CloudEvents extensions will be picked up by ALL receivers.  W/o this PR, it's possible for someone to define a CE extension that maps to an existing HTTP header (like `datacontenttype` does) and because …

make extensions follow the same pattern as normal attrs

---

README.md
SDK.md
adapters/aws-s3.md
adapters/github.md
adapters/gitlab.md
amqp-format.md
amqp-transport-binding.md
avro-format.md
extensions/dataref.md
http-transport-binding.md
http-webhook.md
json-format.md
kafka-transport-binding.md
mqtt-transport-binding.md
nats-transport-binding.md
primer.md
roadmap.md
spec.avsc
spec.md

- s/0.4-wip/1.0-rc1/
- s/URI-reference/URI/ in scheme section for spec.md - per issue #511 since it
was just a typo
- updated Roadmap to say we completed 1.0-rc1 milestone

Modify docs for v1.0-rc1 release

---

primer.md

- removed:
```
The specification places no restrictions on the type of the extension	
attributes. Meaning, they may be simple types (e.g. strings, integers), complex	
(e.g. structured) or undefined collection of attributes.
```
- ran lint.
Signed-off-by: Scott Nichols <nicholss@google.com>

Remove unrestricted extensions. Lint.

---

spec.md

Clarify the meaning of missing datacontentype, when it is allowed, and what that means when translating events between formats/protocols.
Also replaced "transport" with "protocol" everywhere, I believe that is now the preferred term. "Transport" is not defined in the terminology.
Fixes #520

Clarify meaning of missing datacontentype.

---

avro-format.md

This PR updates the example for 'application/avro' content data where it should be written using the Avro `bytes` type.
Closes #515

Update example for 'application/avro' content

---

http-webhook.md

I removed a requirement that a sender MUST NOT send notifications in case of denial by the target, as there is no way for the sender to distinguish denial from a target just not supporting the handshake. As the validation request is mostly about protecting the sender, the statement was unnecessary.
If people come to the conclusion that the statement should not be removed, we need some clear way to distinguish the validation response of a target that does not support validation and a target that denies event delivery.
This PR solves #328

Removed statement about denial

---

spec.md

Fixes #508
Signed-off-by: Alan Conway <aconway@redhat.com>

Clarify interoperability of extensions (#508)

---

documented-extensions.md
extensions/distributed-tracing.md
extensions/partitioning.md
extensions/sampled-rate.md

As we recently added a definition for _event format_ that mentions _stand-alone event formats_ to the spec, I changed the wording in the descriptions of extensions from _in-memory_ format to "stand-alone event format" to better reflect this.
@alanconway What do think?

"Stand-alone event format" instead of "in-memory format"

---

primer.md

This PR makes the CE primer a tiny bit prettier via syntax highlighting.

Add highlighting to Primer JSON snippets

---

extensions/distributed-tracing.md

The w3c spec links were out-of-date.

Update Distributed Tracing extension spec links

---

extensions/distributed-tracing.md

Per https://w3c.github.io/trace-context/#value, tracestate values must
not contain (,) or (=) characters.
Signed-off-by: Ian Milligan <ianmllgn@gmail.com>

Fix distributed tracing example.

---

README.md

Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>
(note this is for v1.0 branch)
Adds the missing v1.0 links for:
* AVRO Event Format
* Kafka Protocol Binding

[v1.0] Adding v1.0 links for Avro and Kafka

---

kafka-protocol-binding.md

Closes https://github.com/cloudevents/spec/issues/570

Specify encoding of kafka header keys and values and message key

---

proprietary-specs.md

- Adding link to Google Cloud Pub/Sub binding in the proprietary specs file.

Adding link to Pub/Sub binding

---

amqp-protocol-binding.md
http-protocol-binding.md
kafka-protocol-binding.md
mqtt-protocol-binding.md

Add some guidance for how to determine when an incoming message is a binary
CE vs some random non-CE message. The same receiver might accept CE and non-CE
messages so we should have an interoperable way for them to know what they're
getting.
If people are ok with this general direction then I can make the same change to the other transport specs.

How to determine binary CE vs random non-CE message

---

proprietary-specs.md

Introduced language to guide the inclusion of proprietary binding specifications

Proprietary binding spec inclusion guide

---

primer.md

As a recent entrant into the SIG I thought it would be a good opportunity to read through all the documentation and to suggest 
improvements where appropriate.

Minor updates to Cloud Events Primer

---

extensions/distributed-tracing.md

Reworked Distributed Tracing Extension

---

subscriptions-api-openapi.yaml

Remove `example: null` to enable it in Azure API Management import.
Fix for issue #606
Signed-off-by: Thomas Weingartner <thomas.weingartner@gmx.ch>

Fix invalid example in subscriptions-api-openapi.yaml

---

spec.avsc

Change CloudEvent to AvroCloudEvent
Signed-off-by: Fabio José <fabiojose@gmail.com>

Closes #615

---

discovery.md

Closes: #622 
Clean-up - Just removing a term that is unused - we can add it back later if needed.

Remove unused 'subscriber'

---

discovery.md
tools/verify-links.sh

Closes #621
And moved a few terms to order them in the order in which the event flows,
starting with the Service.  If people want alphabetical, I'd be ok with that
too.

Add pointers to CE terms in CE spec

---

amqp-protocol-binding.md
http-protocol-binding.md
kafka-protocol-binding.md
mqtt-protocol-binding.md

Clarified MUST requirement for JSON format

---

discovery.md

- Restructued things so that it didn't feel like we were repeating the
definition of the attributes. For example, we now just define Service
and its attributes once and then simply point back to that, and its
serialization, from the Query section
- got rid of "provider" in the model. Technically, that's an impl detail
and consumers should not care what generated the CE - it's things like
the source and service that they'll care about (or even know about)
- introduced the term "Discovery Endpoint" as the "thing" that implements
the spec
- started an JSON encoding definition
- Modified the query stuff so that all data is returned in one shot.
I believe the current spec implied that people would need to do one
query to get the list of Types of interest and then another one to pull
back the …

Discovery Revamp

---

schemaregistry/schemaregistry.md
schemaregistry/schemaregistry.yaml

For initial review. I'm still updating both documents including changing some names, but the combination of OpenAPI doc and the spec doc should already tell a fairly complete story. 
Microsoft proposal for #610

Schema Registry Proposal

---

community/demos.md

Link providing a demo for Cloud Events orchestration. Follow up example will come with Knative.

Adding Demo for Cloud Events Orchestration

---

discovery.md

This PR adds the property _sourcetemplate_ to the eventprovider that provides a means to describe how the `source` attribute of a service/eventprovider will look like. It is referring to [RFC 6570](https://tools.ietf.org/html/rfc6570) which is also referenced by the definition of parameters in OpenAPI.

Add property "sourcetemplate" to eventprovider/service

---

governance/SDK.md

As discussed in CloudEvents WG Meeting June 18, 2020, I started drafting some bits about the sdk projects governance, in particular regards:
* Keeping the projects healthy
* Handling situations where maintainers are not active
* Voting process
This PR doesn't cover the add/remove maintainers policies, which IMHO deserves a separate discussion, but the proposed document is meant to host them (I've added a blank section for them) 
All the numbers are drafted, I focused mainly on the criteria and the process.

SDK governance draft

---

discovery.md

While implementing the discovery spec: https://github.com/cloudevents/sdk-javascript/pull/236
I notice the result of /types/* endpoint seems to be map instead of array, not sure if the intent was a map but seems more logical to me so did the change this way.
Another question that raised was the permission scheme, as I was unsure if we needed to filter types within the service object based on permission, I did implement this type of filtering as I supposed it is a possibility that we want to restrain the types of event visible for some audience

typo and return type mismatch on /types endpoint for discovery spec

---

ce_discovery.yaml

Add a first version of an OpenAPI specification for the Cloud Events discovery API. It is based on the [discovery spec](https://github.com/cloudevents/spec/blob/master/discovery.md) and includes already changes from PR #664.
Signed-off-by: Thomas Weingartner <thomas.weingartner@gmx.ch>

[Discovery] Add ce_discovery.yaml

---

community/SDK-GOVERNANCE.md

This PR adds 2 paragraphs to the sdk governance doc:
* definition to add new maintainers
* definition on how to modify the sdk governance doc itself

New sdk maintainers rules

---

ce_discovery.yaml
discovery.md

Fixes: https://github.com/cloudevents/spec/issues/685
Fixes: https://github.com/cloudevents/spec/issues/684
Fixes: https://github.com/cloudevents/spec/issues/679
- Rename services types[].type to types[].name
- Drop /types endpoint
Signed-off-by: Scott Nichols <snichols@vmware.com>

Rename services types[].type to types[].name; Drop /types endpoint

---

subscriptions-api.md

there was a trailing comma in the json example for Subscription Filters.
Was,
```json
"filters": [{
"type": "exact",
"property": "type",
"value": "com.example.my_event"
},
{
"type": "suffix",
"property": "subject",
"value": ".jpg"
},
]
```
Now:
```json
"filters": [{
"type": "exact",
"property": "type",
"value": "com.example.my_event"
},
{
"type": "suffix",
"property": "subject",
"value": ".jpg"
}
]
```
Then, ran the prettier lint on the subscription api markdown file.

[Subscription] drop extra comma in json example, lint

---

discovery.md

Per @n3wscott's suggestion, this adds a new attribute that can be used to
know when an entry has been updated. It can be used as an e-tag type of
thing or to know when, during an import, the entity being imported is
older than what the discovery endpoint already has.
I wasn't sure if a counter or a timestamp would be better, so I added
both so people can see how both look.
I'm leaning more towards a timestamp since it give a bit more information.

Add a version/timestamp attribute

---

json-format.md

The spec currently uses ticks around `data` as if this is a literal field.
This isn't quite accurate, we don't mean the literal key `data`. We state the data can be stored in `data` or `data_base64 ` right after, so it's a little confusing saying `data` before. I suggest removing the ticks to make this clearer.
See the diff to understand the change the best.
Related: https://github.com/cloudevents/spec/issues/520

docs: do not use code ticks for data that may actually be data_base64

---

discovery.md

Minor wording change to ensure that people know that this URL points to the Service entry in the Discovery Endpoint and NOT to the Service itself

tweak url description

---

discovery.md

The dataschema description in discovery has a link to dataschema in the spec.
The link is named datacontenttype (however the link target is correct).
Signed-off-by: Manuel Stein <manuel.stein@nokia-bell-labs.com>

discovery: fix dataschema description

---

websockets-protocol-binding.md

Tweak the WS protocol binding to support protobuf fomat.

Add protobuf format as a sub-protocol

---

subscriptions-api-openapi.yaml

Signed-off-by: Remi Cattiau <remi@cattiau.com>
Current spec is using GET/DELETE/PUT/POST on /subscriptions with id url parameter or id in body.
This PR move to:
GET /subscriptions: List subscriptions
POST /subscriptions: Create subscription
GET /subscriptions/{id}: Retrieve a subscription
PUT /subscriptions/{id}: Update a subscription
DELETE /subscriptions/{id}: Delete a subscription
Some questions popped while working on it: 
- in my opinion, the proxy settings should be the application choice, not the subscription choice.
- the creation request should not contain an id, as the id should be generated by the application (so I added a SubscriptionRequest schema)

refactor: change subscription API to resource based

---

discovery.md
subscriptions-api.md

- fixed psuedo schema in discovery - config has 'types' not 'values
- typos
- clarify that URL points to the DE entry and not the actual service
- show sample JSON serializaton of a Subscription
- outline for HTTP REST API
- move "dialect" under "filter"
- s/filter/filters/
- make "dialect" an URI-reference
- add "subscriptiondialects" to the DE spec

Minor tweaks in prep for interop

---

primer.md

in #703 it was asked to mandate certain fields in the spec to enhance the security model, However based on the discussion we all came to a conclusion that the spec doesn't have to get into the security business. Hence, the Group decided to add this information into the Primer.

[Primer] Adding a Non-Goal w.r.t Security

---

community/contributors.md

Reviewing the changes since 1.0, I realized that I wasn't on the contributors doc. Not a big deal, but thought I would go ahead and add myself. It doesn't appear that names are in any particular order, so I just put myself at the bottom of the Red Hat list.
Signed-off-by: Lance Ball <lball@redhat.com>

docs: add lance to community/contributors.md

---

http-protocol-binding.md

Signed-off-by: Carlos O'Ryan <coryan@google.com>

fix: incorrect name for reference link

---

extensions/distributed-tracing.md
http-protocol-binding.md
kafka-protocol-binding.md
mqtt-protocol-binding.md
proprietary-specs.md
protobuf-format.md
websockets-protocol-binding.md

This commit addresses a few typos and does a little wordsmithing on some
of the docs and specs meant to land in the 1.1 release.
In the proprietary-specs.md document, I used MUST in a couple of places.
Not sure if this is appropriate for that doc.
Signed-off-by: Lance Ball <lball@redhat.com>

docs: typos and wordsmithing for 1.0.1

---

schemaregistry/schemaregistry.md

To get a specific schema version, the URI is donated as `/schemagroups/mygroup/schemas/myschema/versions/myversion` may more reasonable.

Fix version URI typo for the 3.4.2 section

---

subscriptions-api-openapi.yaml

fixes #758 
- fix "required: false" on path parameters which can't be omitted
- missing required field for body of creating and updating operation
- use oneOf instead of anyOf

Subscription OAS use of required and anyOf

---

primer.md

Alternative to #741 - dealing with errors

---

subscriptions-api-openapi.yaml

Changes based on our discussions, fixes required for unambiguous code-gen, adding credential types for outbound push-delivery
- Proper operationIds
- New subscription object attributes
- Rearranged protocol settings such that they inherit from a common base
- Introduced the "basic" filters as distinct filter types
- added "all", "any", "not" filters
I've done some validation of the spec with the Swagger code generator and NSwag. For most languages, the output for the polymorphic constructs like filters and protocol settings and credentials is as expected, meaning that the protocol settings and credentials form a class hierarchy and the generated filter objects can form a graph.

Subscription API Changes based on deep-dive

---

amqp-protocol-binding.md

Signed-off-by: Eric Bariaux <375613+ebariaux@users.noreply.github.com>

Fixed typo in AMQP mapping spec

---

schemaregistry/schemaregistry.md

As per title, fx typo in schema registry spec, schwema -> schema.

Fix typo in schema registry spec

---

kafka-protocol-binding.md

This came out after the discussions in https://github.com/cloudevents/sdk-java/pull/260
The problem with partition key extension is that it must be used in the right context and it should not be a default (or opt-out) behaviour, but it should be a very precise opt-in behaviour that only users "aware of the consequences" should adopt it.  

Clarify the role of partitioning extension in Kafka

---

community/SDK-GOVERNANCE.md

Per the rules, I think this requires a 1 week vote.
All SDK maintainers can vote.
Vote closes on Monday Mar 8, 3:30pm ET
/cc @cloudevents/sdk-maintainers 

Add rules for adding new SDKs

---

.github/workflows/commitlint.yaml
community/CONTRIBUTING.md

Per issues:
- https://github.com/cloudevents/spec/issues/755
- https://github.com/cloudevents/spec/issues/687
It is difficult to determine the differences between spec versions and progression to the spec as time goes on.
---
One way we can help developers understand the spec changes is by using and enforcing [conventional commits](www.conventionalcommits.org).
With these types of commits, we can generate more detailed changelogs in the future. Unfortunately, there's not a whole lot we can do with unstructured commit messages from the past.
This PR adds a GitHub Action to this repo to add a check to pushes and pull requests to see if the last commit is a conventional commit. Note: PRs when squashed and merged can use a single commit message.
- Adds `.github/workflows/commitlint.yaml`
- …

ci: conventional commits

---

expression-language.md

Allow the expression to return any value, not just boolean.
This makes the language usable for a broader range of use cases, but at the same time I clarify that for filtering, the return value should always be bool (either is bool, or it must be casted to bool)

[CESQL] Return any value

---

expression-language.md

The `IN` operator semantics were unclear, in particular its relation with the implicit type casting rule.
This clarification specified that no implicit casting rules are applied for `IN`, that is:
```
'123' IN (123)
```
Evaluates to `FALSE`. One can rewrite this expression using explicit cast, like:
```
'123' IN (STRING(123))
```

[CESQL] Clarification of the IN semantics

---

protobuf-format.md
spec.proto

feat: Add specification for protobuf batch format.
Extend protobuf format specification to include a batch format for protobuf. 
Closes #794 

Add support for protobuf batch format

---

expression-language.md

This definition of casting functions is more flexible and allow roundtripping and identities. E.g. without this definition, this should fail per spec:
```
STRING('abc')
```
And this requires an unnecessary casting:
```
INT(10)
```

[CESQL] Define casting functions as accepting Any as input

---

http-protocol-binding.md

Fixes #777
Once this is agreed, we should also document conformance tests, but
it's unclear at the moment where they should live.

Clarify HTTP header value encoding and decoding requirements

---

primer.md
spec.md

docs: Expand versioning suggestions

---

subscriptions-api.md

The `all` and `any` combinators enforces too strict constraints on the actual evaluation of the filter. I propose to remove them, since they may impede any eventual optimization in the evaluation of filters

[Subscriptions API] Remove strong constraints on filter combinators

---

subscriptions-api.md

This PR modifies the shape of the `filter` subscription request attribute to an array of filter expressions:
This:
```yaml
filter:
exact: ...
```
Becomes this:
```yaml
filters:
- exact: ...
```
The reason to introduce this change is to improve ergonomics of the filter usage in most use cases, where at the top level the user wants to do an and of several filters. In other words this:
```yaml
filter:
all:
- exact: ...
- prefix: ...
```
Can be written as:
```yaml
filters:
- exact: ...
- prefix: ...
```
It also renames `filter` to `filters`, in order to be more consistent with the change itself.
The openapi schema change is going to be introduced in another PR.

[Subscriptions API] Multiple dialects in the filter object

---

ce_discovery.yaml

Several tools are unhappy with missing operation ids in OpenAPI and will generate rather unpleasant names for proxies.

Adding operation ids to discovery contract

---

http-webhook.md

As @schabungbam pointed out, there was an inconsistency in one example that is fixed with this PR.
@duglin Should this also be cherry-picked into 1.0.1, as it is just about a typo?
Signed-off-by: Klaus Deißner <klaus.deissner@sap.com>
Fixes #673

Fix for #673 - WebHook-Allowed-Origin

---

discovery.md

Follow up to #837 
Example `POST /services` and `POST /services/{id}` response must
reflect changes too.

bug (discovery): update example response

---

spec.md

Fixes #
To consistently use punctuation throughout the spec, fix typo in `datacontenttype` section.
- Add missing period (".").
N/A

Update punctuation (period) in dataconenttype section

---

json-format.md

Fixes #558
Fixes #860
This is an attempt to clarify the interpretation of the `data` member in JSON Format in the case of a JSON-oriented `datacontenttype` vs a non-JSON-oriented `datacontenttype`. It also explicitly documents in json-format.md the implied `datacontenttype` value should the attribute be omitted.

fix(json-format): Clarify data encoding in JSON format with a JSON datacontenttype

---

README.md
SDK.md

Fixes #874
- Add PowerShell SDK to the list of SDKs
```release-note
```

Add PowerShell SDK to the list of SDKs

---

spec.md

The RefinedGitHub plugin strips off the https:// otherwise, and they aren't meant to be clickable anyway.

Use code formatting for example URLs

---

discovery.md

During interop testing someone was returning a 404 when the query yielded zero results. It shouldn't be an error.

Make it clear that empty query is still a 200

---

expression-language.md

Signed-off-by: Remi Cattiau <remi@cattiau.com>
- Remove explicit casting from the spec in favor of implicit casting
The functions like IS_BOOL were not usable as is, we have no IF within the language.
Discussed last week on the call, but I'm happy to not merge if we have use case of explicit casting, I did not find one

feat(cesql): remove explicit casting from the spec

---

community/open-source.md

Signed-off-by: Scott Nichols <scott@chainguard.dev>
- Removed refs in the open source page where the integration did not support v1.0 of the CloudEvents spec.
- Added some simple headers to sort the content.
```release-note
Cleaned up the open-source.md page.
```

Removing old additions to the page, adding 1.0 requirement.

---

README.md

This change makes it clear that the Javascript SDK supports TypeScript.  In fact, it is written in TypeScript.
This just saves people the time of digging into the repository of the Javascript SDK to see whether it includes any TypeScript
definitions.
- Update README to indicate SDK supports TypeScript
No need to update any release notes.

Indicate TypeScript support

---

cloudevents/SDK.md

Fixes # https://github.com/cloudevents/spec/issues/910
- A very minor clarifying change to the wording of the SDK requirements to make it more consistent with the HTTP transport specification.

chore: tweak SDK requirements wording

---

cesql/spec.md

Fixes #
This PR  fixes a link in the CE SQL spec that was broken during the latest repository restructuring.

Fix broken link to section about filter dialects

---

discovery/spec.md

Doesn't seem right to use POST to update (add) a new Service when the ID is already known.

Use PUT instead of POST

---

README.md
cesql/spec.md
cloudevents/SDK.md
cloudevents/adapters.md
cloudevents/adapters/aws-s3.md
cloudevents/bindings/amqp-protocol-binding.md
cloudevents/bindings/kafka-protocol-binding.md
cloudevents/bindings/mqtt-protocol-binding.md
cloudevents/bindings/nats-protocol-binding.md
cloudevents/bindings/websockets-protocol-binding.md
cloudevents/formats/avro-format.md
cloudevents/formats/json-format.md
cloudevents/formats/protobuf-format.md
cloudevents/primer.md
cloudevents/proprietary-specs.md
cloudevents/translated/zh-cn/README_CN.md
community/CONTRIBUTING.md
community/GOVERNANCE.md
community/SDK-GOVERNANCE.md
community/SDK-PR-guidelines.md
community/SDK-maintainer-guidelines.md
community/demos.md
discovery/primer.md
misc/Makefile
misc/roadmap.md
misc/tools/verify-links.sh
misc/tools/verify-specs.sh
schemaregistry/spec.md

- Add support for href checking bookmarks & fixed bad links
- Speed up the checkers.
- Change Makefile so that it checks ALL files w/o needed to state which ones. So, now we have a flag in each md file that we DON'T want checked instead. We were missing some files. Look for the ``  line
- fixed some RFC keywords that were not checked before

Add checks for bookmarks & fix bad links

---

cloudevents/formats/cloudevents.proto

The naming choice is based on the C# SDK core being
"CloudNative.CloudEvents". This creates a bias towards using the C#
SDK instead of "roll-your-own" - but I think that's okay,
personally. Happy to consider other options.
- Add a C# namespace option to cloudevents.proto
```release-note
Adds a C# namespace option of `CloudNative.CloudEvents.V1` to the proto representation.
```

Add C# namespace option to proto

---

.github/pull-request-template.md
.github/workflows/release-notes.yaml
README.md
cesql/spec.md
cloudevents/bindings/amqp-protocol-binding.md
cloudevents/bindings/http-protocol-binding.md
cloudevents/bindings/kafka-protocol-binding.md
cloudevents/bindings/mqtt-protocol-binding.md
cloudevents/bindings/nats-protocol-binding.md
cloudevents/bindings/websockets-protocol-binding.md
cloudevents/formats/avro-format.md
cloudevents/formats/json-format.md
cloudevents/formats/protobuf-format.md
cloudevents/http-webhook.md
cloudevents/primer.md
cloudevents/spec.md
cloudevents/translated/zh-cn/README_CN.md
discovery/primer.md
discovery/spec.md
misc/RELEASE_NOTES.md
misc/roadmap.md
schemaregistry/spec.md
subscriptions/spec.md

- Sync with v1.0.2 - 'main' is missing a lot of admin files
- update refs from v1.0.1 to v1.0.2
- update titles from v1.0.2-wip to v1.0.3-wip

Sync with v1.0.2

---

cloudevents/spec.md

Added a section to define a set of context attribute names
that cannot be used.
- Introduces the concept of reserved attribute names that cannot be used.
```release-note
`data` is now reserved and MUST NOT be used as an extension attribute name.
```

Introduce reserved attribute names.

---

cloudevents/formats/json-format.md

Fixes #933 and #934
- Clarify that the "default to JSON" handling of datacontenttype
does not apply to binary data
- Give an example of a JSON number as the `data` property value
```release-note
Clarifications to JSON format data/data_base64 handling
```

Clarifications to JSON format

---

subscriptions/spec.md
subscriptions/subscriptions-openapi.yaml

To improve the usage of the API in the common case, I'm removing
the restriction for `exact`, `prefix` and `suffix` filters of only
containing exactly one attribute.
When multiple attributes are specified, all attributes must match (
like in [1]), for example, these filters:
```yaml
filters:
- suffix:
type: "com.github.push"
- suffix:
subject: "https//github.com/cloudevents/spec"
```
can be written as:
```yaml
filters:
- suffix:
type: "com.github.push"
subject: "https//github.com/cloudevents/spec"
```
[1]: https://github.com/cloudevents/spec/pull/803
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>
- Remove exactly one attribute restriction for exact, prefix and suffix filters
```release-note
Remove exactly one attribute restriction for exact, prefix and suffix …
```

[Subscription] Remove exactly one attribute restriction for exact, prefix and suffix filters

---

cloudevents/formats/json-format.md
community/contributors.md
misc/tools/verify-links.sh

I think github thinks we're ddos-ing it with all of these GETs so let's just
skip the file since it's not that important anyway.
Signed-off-by: Doug Davis <duglin@gmail.com>

Skip problematic file during link check

---

cloudevents/SDK.md

Per a chat we had in a previous SDK call, the SDK SHOULD validate attributes
so users can be notified if they gave an invalid value.
Signed-off-by: Doug Davis <duglin@gmail.com>

SDK should validate context attribute values

---

cloudevents/spec.md

Fixes #955
Signed-off-by: Doug Davis <duglin@gmail.com>
```release-note
Add some text to explain why we're so restrictive on attribute names
```

Add some reasoning to why we limit things.

---

README.md
cloudevents/working-drafts/xml-format.md

feat: Introduce XML Format
Adds support for XML as a format for CloudEvents (including batch format), XML schema provided along with textual specification.
Closes #662 

Introducing XML Format.

---

cloudevents/bindings/kafka-protocol-binding.md
cloudevents/primer.md
cloudevents/spec.md

Per [this chat](https://github.com/cloudevents/spec/pull/972/files#r829061428), we should be very clear that each CE attribute can only appear at most once in an Event. While this introduces a MUST, it doesn't change the semantics of our intent and therefore could be seen as a clarification (or bug to not have had this in the past).
```release-note
Make it clear each CE attribute can only appear at most once per event
```
/cc @jskeet

Make it clear each CE attribute is a singleton

---

README.md

Before, `README.md` would link "Protobuf Event Format v1.0.2" to the NATS protocol binding.

README.md: fix link to protobuf format spec

---

cloudevents/working-drafts/xml-format.md

These represent the following clear votes from #998:
- Example 2: text node in an `<event>` element
- Example 5: element within a context attribute element
- Example 6: element within binary `<data>` element
- Example 7: element within a text `<data>` element
- Example 8: text within an "any" `<data>` element
- Example 10: text node in a `<batch>` element
- Example 12: comments are allowed anywhere
The remaining examples did not have clear-cut votes, although it
looks like we *probably* want to prohibit additional XML attributes
within context attribute elements.

Next round of restrictions in XML format

---

discovery/discovery.yaml
discovery/spec.md

Based on last week's call I updated our "epoch" processing for the APIs to be more consistent:
- epoch is used for version checking. If present on the request then the current value in the DE must match
- PUT is used to update - not create
- POST is used for create or update (mainly for bulk update)
- import/sync'ing is no supported (and I removed any text that implies it)
- I removed the ability to specify the same Service more than once in a POST or DELETE
We can add import/sync support in another PR.
OLD:
Also:
- reject requests if the passed-in epoch value doesn't exactly match current value
- make DELETE idempotent by returning a 200 (instead of 404) of the Service is already deleted
- removed the Body on the `DELETE /services/ID` since we don't really need it if we have the query …

Update processing of Epoch on all operations

---

schemaregistry/spec.md

Fixes #
Fixes a grammatical typo error in the schema registry spec doc.
- simple markdown edit
```release-note
```

docs: fix typo in schema registry spec

---

cloudevents/bindings/kafka-protocol-binding.md

Fixes #591
```release-note
Allow for non-JSON formats (e.g. Avro) with older version of Kafka
```

Remove hardcoded reference to JSON since we have Avro now

---

cloudevents/extensions/sequence.md

Alternative to #1026
@BenBeattieHood @jroper comments?
@jroper I know you'd like to remove the "lexicographical" stuff, but I couldn't bring myself to do that yet... baby steps :-) 
Fixes #923
- Remove SequenceType from Sequence extension
```release-note
Remove the SequenceType attribute from the Sequence extension to simplify things. Also added text to make it clear that "padding" might be needed to ensure the values can be compared properly.
```

Clean-up of Sequence

---

cloudevents/spec.md

Fixes #1044
- Change the word "needs" to "SHOULD" under the [Notational Conventions](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#notational-conventions) section in the CloudEvents spec to avoid ambiguity 
```release-note
Change the word "needs" to "SHOULD" under the Notational Conventions section in the CloudEvents spec to avoid ambiguity 
```

fix: use SHOULD instead of needs

---

cloudevents/adapters/aws-sns.md

Recently, I need to convert SNS messages into CloudEvents. I thought this might be a common case for other folks.
So I propose this adapter to describe how to convert SNS messages into CloudEvents. 
All Suggestions are extremely welcome.
Signed-off-by: Jie Ding <jie.ding@linkall.com>

adapter: add aws-sns-adapter

---

cloudevents/languages/zh-CN/spec.md

Signed-off-by: Ranger Tsao <cao.zhifu@gmail.com>
fix some typo and one broken link

spec: fix some typo in chinese translation

---

cloudevents/primer.md

Clarify that CE doesn't define this correlation stuff, but it could be an extension.
Primer has this text:
- - -
"An event sent from a source may result in a sequence of additional events sent from various middleware devices such as event brokers and gateways. CloudEvents includes metadata in events to associate these events as being part of an event sequence for the purpose of event tracing and troubleshooting."
- - -
And someone on Slack asked "what metadata?"

Clarify Primer around tracing correlation

---

registry/README.md
registry/spec.md
tools/verify.py

This PR shows an idea we've been thinking of where we abstract both the Discovery Service and the Schema Registry into one high-level Registry type of spec. We think this will work because both specs have similar concepts of "groups" and "resources" in those groups. This would then allow the generic spec to be customized for particular domains... endpoint discovery and schema registry in our case. This would also then potentially allow us to work with other projects like [Apicuri](https://www.apicur.io) to enhance community alignment.
This is a very rough draft but should show the direction so people can let us know if this seems like an ok way to go.

Proposed "Registry" spec

---

README.md

Existing link for some reason doesn't show latest videos
Signed-off-by: Jesse Menning <62108913+jessemenning@users.noreply.github.com>
Fixes #
-
-
-
```release-note
```

Change link location for meeting recordings

---

cloudevents/working-drafts/xml-format.md

- Unknown attributes and elements in a different namespace should be ignored (other than within a data element)
- Make it clear that "XML data" is really a representation of a single XML element.
Closes #998.
Closes #1005.

Clarify XML format specification

---

cloudevents/spec.md

Fixes #1072
```release-note
Make it clear that `datacontenttype` MAY appear even when `data` is not present.
```

Make it clear that datacontenttype MAY appear w/o data

---

cloudevents/bindings/http-protocol-binding.md
cloudevents/spec.md

The restriction in terms of uniqueness is new, and definitely open for debate. I had previously always just assumed it. If we choose not to require it, we should explicitly permit duplicates.

Move batch restrictions from HTTP to the main spec

---

cloudevents/working-drafts/xml-format.md

(We should definitely have a big conformance suite for this format at some point...)
The repetition of the language around XML element data is deliberate, but slightly clunky. Other suggestions welcome.
Also happy to add an example with both CDATA and a text node if that would be useful, but it feels like it's probably better in a conformance test.
This is an alternative to #1143, and I believe would fix #1013.
Initial review requested from Jem, and we can go on from there.

Clarify CDATA handling in XML format

---

cloudevents/working-drafts/xml-format.md

Fixes #1004.
I wasn't sure whether providing the parenthetical example was useful - I hope so. We could go further and explain *why* we prohibit line breaks (i.e. because no valid attribute value can ever contain a line break) but I wasn't sure whether that was worth it.

Specify the policy for whitespace in XML format attributes

---

registry/README.md
registry/samples/contoso-crm.cereg
registry/samples/contoso-crm.cereg.yaml
registry/schemas/generate_openapis.sh
registry/schemas/xregistry_endpoint_protocol_options.json
registry/schemas/xregistry_endpoint_registry.json
registry/schemas/xregistry_endpoint_registry_amqp.json
registry/schemas/xregistry_endpoint_registry_http.json
registry/schemas/xregistry_endpoint_registry_kafka.json
registry/schemas/xregistry_endpoint_registry_mqtt.json
registry/schemas/xregistry_endpoint_registry_nats.json
registry/schemas/xregistry_messagedefinition_definition.json
registry/schemas/xregistry_messagedefinition_registry.json
registry/schemas/xregistry_messagedefinition_registry_amqp.json
registry/schemas/xregistry_messagedefinition_registry_cloudevents.json
registry/schemas/xregistry_messagedefinition_registry_http.json
registry/schemas/xregistry_messagedefinition_registry_kafka.json
registry/schemas/xregistry_messagedefinition_registry_mqtt.json
registry/schemas/xregistry_messaging_catalog.json
registry/schemas/xregistry_openapi.json
registry/schemas/xregistry_openapi_endpoint.json
registry/schemas/xregistry_openapi_messagedefinition.json
registry/schemas/xregistry_openapi_schema.json
registry/schemas/xregistry_openapi_template.json
registry/schemas/xregistry_openapi_template_endpoint_registry_sed_args.txt
registry/schemas/xregistry_openapi_template_messagedefinition_registry_sed_args.txt
registry/schemas/xregistry_openapi_template_schema_registry_sed_args.txt
registry/schemas/xregistry_resources.json
registry/schemas/xregistry_schema_registry.json
registry/spec.md

- Schema Registry section complete 
- Message Definitions section complete
- Endpoint Registry started
Covers CloudEvents, AMQP, MQTT (3.1.1/5.0) as transports
Covers JSON, XSD, Avro, Proto as schema formats
Plan to extend out to the remaining transports we supprt with CE after completing the initial draft.

Group/Resource/Format Details for Registry

---

cloudevents/working-drafts/xml-format.md

Explanation: we view the CE namespace as "owned" by this spec, so while we allow for non-CE-namespaced elements in the batch to be present and ignored, there shouldn't be any elements in the CE namespace other than "event". (We don't permit nested batches, for example.)
Conformance tests in https://github.com/cloudevents/conformance/blob/format-tests/format/xml/invalid-batches.xml#L37
(Also a typo fix.)

Prevent CE-namespaced elements other than event in an XML batch.

---

registry/spec.md
tools/verify.py

- Add support for ?model
- Add a Schema URL for the entire registry as part of the model
- Elaborate on ?inline=PATH
- s/version/versionID/, and remove "version" field from Version resource since
`id` is now its version string
- fixed the spec verification tool so it doesn't flag optional query parmeters
as markdown bookmarks (e.g. [?inline])
- define the 3 properties for each collection (xxxsUrl, xxxsCount, xxxs)

xReg - Lots of changes

---

cloudevents/proprietary-specs.md

(This completes the long-standing AI in the weekly meeting agenda.)

Update Google Pub/Sub binding link to new location.

---

cloudevents/documented-extensions.md
cloudevents/extensions/recordedtime.md
cloudevents/languages/he/extensions/recordedtime.md
cloudevents/languages/zh-CN/extensions/recordedtime.md

This extension defines an attribute that represents the time when an occurrence was recorded in a particular event, i.e. the time when the CloudEvent was created by a producer.
This enables bitemporal data to be represented with CloudEvents which enables several use cases described in the specification of the extension attribute.
Fixes #1200
- Add the `recordedtime` extension attribute.
Extension attributes are not tracked in the release notes as far as I know, so I'm eliding this. If it is needed let me know.

feat: add the `recordedtime` extension attribute

---

cloudevents/documented-extensions.md
cloudevents/extensions/expirytime.md
cloudevents/languages/he/extensions/expirytime.md
cloudevents/languages/zh-CN/documented-extensions.md
cloudevents/languages/zh-CN/extensions/expirytime.md

This extension provides a mechanism to hint to consumers or intermediaries a time after which an event may be ignored.
See linked issue and spec document for reasoning and use cases.
Fixes #1205
- Add an `expirytime` extension attribute
N/A

feat: add the `expirytime` extension attribute

---

OWNERS
README.md
docs/GOVERNANCE.md

Misc edits per the TAG Contrib Strategy Review: https://github.com/cncf/tag-contributor-strategy/pull/509

Changes per TAG Contrib Strategy review

---

docs/SDK-GOVERNANCE.md

To address the governance review: https://github.com/cncf/tag-contributor-strategy/pull/509

Proposed alignment of SDK governance files

---

subscriptions/spec.md

Fixes #
#919 
- Split the list of filter dialects into mandatory and optional dialects, where **cesql** is listed as OPTIONAL.
```release-note
Make clear that the support of CESQL is OPTIONAL for implementers of the subscription specification
```

Cesql optional

---

cesql/cesql_tck/like_expression.yaml
cesql/cesql_tck/subscriptions_api_recreations.yaml

Fixes #1225 
- Add tck test cases which verify that the "LIKE" operator works when the operand is not a string and needs to be coerced to string
- Add tck test cases for suffix, prefix, and exact filter implementations
- Add tck test cases for ANDs and ORs of suffix, prefix, and exact filter implementations

Expand tck tests

---

subscriptions/spec.md

Fixes #1221
- Only CESQL results which are the `TRUE` boolean value should pass the filter.
```release-note
Only CESQL results which are equal to the `TRUE` boolean value pass the CESQL subscriptions API filter.
```

SQL filter: Clarify that only boolean TRUE values pass filter

---

cloudevents/extensions/authcontext.md

Issue created for this change: https://github.com/cloudevents/spec/issues/1245
Fixes #
For the recently added extension Auth Context /extensions/authcontext.md the attribute of authtype could be not identified reliable and be unknown.
The key principle here is that authtype classification results should be predictable and should not change. However, for some cases the type is preferred to be unknown when we can't determine reliable. The main concern we have is how authtype classifications might change when we are able to classify the request in the future. As a result if we change from unknown to app_user it is a "breaking" change for API consumers. Since their code may build business logic based on authtype results.
In https://github.com/cloudevents/spec/blob/main/cloudevents/documented-e …

Add unknown value for authtype enum of Auth Context ext

---

cesql/spec.md

Fixes #1232 
Include "TRUE" | "FALSE" when you define boolean literals in the spec.md
```release-note
```

Clarify boolean literals in specification

---

cesql/cesql_tck/subscriptions_api_recreations.yaml

While running the tck tests, I noticed that there were a few mistakes in them. This PR aims to fix those.
- Fix typo of `expresion` -> `expression`
- Fix result of a test case that was incorrectly set to true
- Change CE overrides for another test to make sure that it returns an error, rather than depending on the SDK not optimizing AND evaluation for the error to occur

Small fixes to CESQL tck test cases

---

cesql/cesql_tck/README.md
cesql/cesql_tck/context_attributes_access.yaml
cesql/cesql_tck/subscriptions_api_recreations.yaml
cesql/spec.md

Fixes #1230
- Clarify that missing attributes should not result in an error
Note: this is actually something that the SDKs currently implement incorrectly, so if this PR is merged I will go and fix them.
```release-note
CESQL expressions should not return an error when there is a missing attribute
```

Clarify that missing attributes should not result in errors

---

cloudevents/spec.md

The core specification lacks any recommendation how to cope with a composite `subject` field. Leaving everything to a producer may create an undesirable situation of packing, even semantically similar, `subject` content in arcane manner. 
This PR adds an additional example, suggesting a different way to structure the content of the `subject` field, while fully preserving compatibility with the existing standard.

Suggestion about Structuring a Composite "subject" Field

---

cloudevents/SDK.md
cloudevents/bindings/amqp-protocol-binding.md
cloudevents/bindings/http-protocol-binding.md
cloudevents/bindings/kafka-protocol-binding.md
cloudevents/bindings/nats-protocol-binding.md
cloudevents/spec.md

We don't note what "kind" of case insensitivity to consider though - should we only consider ASCII values as matching
"application/cloudevents" for example? (Case insensitivity is hard, basically...)
There may be other aspects I've missed, or I may have been too aggressive in imposing case-insensitivity in some bindings. Thoughts very welcome.

First pass at considering content-type in a case-insensitive way.

---

cesql/cesql_tck/like_expression.yaml

Follow up on discussion in sdk-go: https://github.com/cloudevents/sdk-go/pull/1046#discussion_r1595307651
- Add a test verifying that an invalid string literal in a LIKE expression is a parse error

test: verify that invalid string literals in LIKE expression are a parse error

---

cesql/cesql_tck/binary_logical_operators.yaml

This is a follow up on #1267 and #1270, to make sure that those changes are included in the tck tests.
- Test that the OR operator is short circuit evaluated
- Test that the AND operator is short circuit evaluated

test: tck tests now check that AND and OR operators are short circuit evaluated

---

cesql/spec.md

Addresses the comments on #1282 
Look at the discussion on #1282

CESQL v1 review changes

---

cesql/cesql_tck/README.md
cesql/cesql_tck/binary_comparison_operators.yaml
cesql/cesql_tck/binary_logical_operators.yaml
cesql/cesql_tck/binary_math_operators.yaml
cesql/cesql_tck/casting_functions.yaml
cesql/cesql_tck/context_attributes_access.yaml
cesql/cesql_tck/integer_builtin_functions.yaml
cesql/cesql_tck/like_expression.yaml
cesql/cesql_tck/negate_operator.yaml
cesql/cesql_tck/not_operator.yaml
cesql/cesql_tck/spec_examples.yaml
cesql/cesql_tck/string_builtin_functions.yaml

With all of the CESQL spec changes recently, the spec needed some updates to reflect what had changed
- Add results to every expression that has an error, as CESQL spec has been clarified on what should happen in that case
- Added missing attribute errors back, as well as tests to ensure that operators handle it correctly
- Add test for the `ABS` function overflow error
- Fix boolean casting now that it is defined for all types

Update CESQL tck tests to match spec changes

---

cesql/spec.md

Addresses https://github.com/cloudevents/spec/issues/1282#issuecomment-2152782563
- Add trailing commas where appropriate after "that is" in the spec (I audited all of them and only found the two mentioned in the original comment as being wrong

fix: add trailing commas where appropriate for 'that is' in CESQL spec

---

cesql/CESQLLexer.g4
cesql/README.md
cesql/languages/zh-CN/spec.md
cesql/spec.md

We'll be using this PR to vote on moving the CESQL to v1.0.
The following community members have voting rights:  Google, IBM/Red Hat, Microsoft, SAP, Mark Peek, Erik Erikson, Tommy Chung.
Other folks are welcome, and encouraged, to vote as well, but only "voting rights" members votes will be counted.
Please vote either with a thumb-up or thumb-down emoji on this comment, or with a new github comment.
The vote will close at the start of the next weekly call - June 13, 12pm ET.
Note: technically, IBM/Red Hat forgot to change their representatives in our tracking spreadsheet so they're not officially listed as having voting rights. However, @Cali0707 has been at the last 4 meetings so Red Hat really should have voting rights. I'll work with Calum on getting the spreadsheet updated. …

Vote: moving CESQL spec to v1

---

README.md
cesql/README.md
cesql/RELEASE_NOTES.md
docs/RELEASES.md

- Add release notes for CESQL v1
- Link to release notes in RELEASES.md
- Align RELEASES.md table

CESQL v1 release notes

---

docs/contributors.md

As decided in the weekly call, I removed the company names and put the names in alphabetical order.

Clean up contributors.md

---

cloudevents/extensions/distributed-tracing.md

Replacement for #912
This follows the same idea/goal as #912 - Point to the OpenTelemetry CloudEvents semantic conventions to help people to understand how to use the extension and how a trace structure should look like in systems using CloudEvents.
I took a slight different approach with this PR where I left most of the existing text. We have now finalized the CloudEvents semconv in OTel. The group there decided to only mention the distributed tracing extension as _an additional_ mechanism to propagate context, but the definition of it should stay here. OTel also doesn't document/specify other means of propagation in messaging systems for example, we rather only mention it. That's why we followed the same for CloudEvents.
The document now points to the CloudEvents OTel semconv which …

docs: link distributed tracing extension to otel semconv

---

cloudevents/extensions/README.md
cloudevents/extensions/deprecation.md
cloudevents/languages/he/extensions/deprecation.md
cloudevents/languages/zh-CN/extensions/deprecation.md

Introduced the `deprecation` attribute to indicate when an event type is deprecated, and added the `sunset` attribute to specify the date and time when the event will become unsupported. This extension provides clear guidelines and examples for implementing these attributes, aiming to improve lifecycle management and ensure better communication with consumers.

Add CloudEvents extension for deprecated events

---

cloudevents/http-webhook.md

Hi!
I've noticed this extra "is" when reading the Web Hooks documentation today.

chore: remove extra 'is'

---

docs/contributors.md

Adding myself to the contributors list. It's a small thing, but since I contributed to the deprecation extension, it's important for me to be included.
Fixes #
-
-
-
```release-note
```

docs: add vandewilly to contributors list

---

cloudevents/primer.md

Use 'that' for a defining clause.

docs: Textual correction

---

cloudevents/extensions/README.md
cloudevents/extensions/data-classification.md
cloudevents/languages/he/extensions/data-classification.md
cloudevents/languages/zh-CN/extensions/data-classification.md

Provides an extension where an event source can annotate an event with
information around data classification of an event and its payload. CloudEvents
may contain payload which is subjected to data protection regulations like GDPR
or HIPAA. For intermediaries and consumers knowing how event payload is
classified enables compliant processing of an event.
Adds an extension with attributes:
- dataclassification (Required). Data classification level of an event and
payload within the context of a data protection regulation.
- dataregulation (Optional). Applicable data protection regulation.
- datacategory (Optional). Data category of the event payload within the 
context of data classification and data protection regulation.

Add data-classification.md extension

---

cloudevents/extensions/data-classification.md

Last remaining issue for PR #1317
ping @JemDay @rob-sessink

Add appendix to data classification extension

---

docs/open-source.md

- Add `Cloud Streams` and `Synapse` as products that use the `CloudEvents` spec
```release-note
Add `Cloud Streams` and `Synapse` as products that use the `CloudEvents` spec
```

Add `Cloud Streams` and `Synapse` as products that use the `CloudEvents` spec

---

docs/open-source.md

This PR does two things:
8fdfc338d729f4089e072287fc0bc0d776a6bf78 Adds CDEvents to the open-source list
1dc4ffbc78f400b9f30ee5106ea4a967e4328ad5 Reformats lines that were greater than 80

Adds CDEvents to docs/open-source.md

---

tools/Makefile
tools/verify.py

This small PR fixes the `bs4` and `pytest` deprecation warnings found in the [CI logs](https://github.com/cloudevents/spec/actions/runs/14521973353/job/40744953269#step:5:27). More specificly:
- Fix the `bs4` deprecation warnings:
```python
/home/runner/work/spec/spec/tools/verify.py:128: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
for a in _html_parser(html).findAll("a"):
```
- Fix the `pytest` deprecation warnings:
```python
/usr/local/lib/python3.13/site-packages/pytest_asyncio/plugin.py:217: 
PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope"
is unset.
```
```release-note
Resolve bs4 and pytest deprecation warnings
```

Resolve deprecation warnings

---

cloudevents/languages/he/working-drafts/asyncapi.md
cloudevents/languages/zh-CN/working-drafts/asyncapi.md
cloudevents/working-drafts/asyncapi-examples/light-switch-events-binary-kafka.yaml
cloudevents/working-drafts/asyncapi-examples/light-switch-events-structured-json.yaml
cloudevents/working-drafts/asyncapi-traits/cloudevents-headers-kafka-binary.yaml
cloudevents/working-drafts/asyncapi.md

Working draft for #1276 
Fixes #1276 
Clarify how CloudEvents headers can be specified in AsyncAPI.
- Add a first draft on how CloudEvents can be specified in AsyncAPI with an example and spec for structured mode with JSON and binary mode with Kafka.
```release-note
Define how CloudEvents headers can be specified in AsyncAPI.
```

AsyncAPI with CloudEvents

---

cloudevents/adapters/github.md

- Adding the missing github events for the github adapter

feat: update github adapter spec

---

README.md
cloudevents/languages/he/v2.md
cloudevents/languages/zh-CN/v2.md
cloudevents/v2.md

ping @jskeet 
If we merge this then we will also close these:
- [Do we want a new optional "mustunderstand" core attribute](https://github.com/cloudevents/spec/issues/1321)
- [Why does the HTTP binding for batch require the same spec version for all events in the batch?](https://github.com/cloudevents/spec/issues/807)
- [handling of datacontenttype is inconsistent](https://github.com/cloudevents/spec/issues/558)
- [fix(protobuf)!: Expose CloudEvent structure with explicit fields](https://github.com/cloudevents/spec/pull/1354)
- [Minor version](https://github.com/cloudevents/spec/pull/1032)
Add the 'v2' label to each one we close

Add a "v2.md" file so we can close v2 issues/PRs

---

cloudevents/extensions/distributed-tracing.md

Ensure `traceparent` isn't an empty string
