CONTRIBUTING.md
README.md
spec.md

rename to cloudevents

---

spec.md

Changed the wording to make it clearer what is being designed and what is being considered as a possible use of context attributes

Changed the wording of context attributes to make it clearer

---

spec.md
use-cases.md

Added some initial use-cases for the OpenEvents specification.
Signed-off-by: Austen Collins <austenATserverless.com>

Add initial use-cases

---

Makefile
spec.md
tools/verify-phrases.sh

Also:
- removed some editorial comments that aren't really appropriate for a spec
- added a tool to verify we upper-case our RFC2119 keywords

First pass at using RFC 2119 keywords

---

tools/verify-links.sh
tools/verify-phrases.sh

Mainly to pickup a fix for when an image as a "title" associated with it.
This was noticed due to Sarah's PR that included an image with a "title" associated with it.

Update the href checker tool

---

CONTRIBUTING.md

Signed-off-by: Malhar Vora <mlvora.2010@gmail.com>

Fix small typo in contribution file

---

CONTRIBUTING.md

Signed-off-by: William Markito Oliveira <markito@redhat.com>

Adding assignment and ownership of work items to CONTRIBUTING.md

---

spec.md

 Make it clear that schema-url is about 'data' and not the entire event 

---

README.md

Add some communication/meeting info to our README

---

spec.md

Closes #59 
Closes #23
Signed-off-by: Yaron Haviv  yaronh@iguazio.com

added content-type attribute

---

README.md

update slack info

---

roadmap.md

addresses #74 -- we didn't actually do all the January items in current roadmap.  
This PR proposes numbered milestones with criteria that I think will help focus our work.

roadmap with numbered milestones

---

LICENSE

I noticed while doing other work that we didn't complete the copyright field within the license. I'm not sure this is a major issue, but I thought I'd submit a PR to discuss any concerns.

Adding Copyright date and owners

---

spec.md

Doing this since our goals/scope statemns seem to cover this now

Remove the 'Status' section of the spec

---

roadmap.md

This minor PR moves all items marked as *Additional* into the versioned stages.  The purpose of this is simply to ensure the additional items completed before certain times to help with publicity of this effort.
Minor clean-ups (e.g. punctuation) have also been added.

Minor Adjustments to the Road Map

---

about/use-cases.md

Signed-off-by: lfourie <louis.fourie@huawei.com>

Added Event Tracing

---

about/use-cases.md

Signed-off-by: cathyhongzhang <cathy.h.zhang@huawei.com>

add a use case for correlation of multiple events

---

serialization.md

Sync up json serialization with latest spec

---

about/contributors.md

Signed-off-by: William Markito Oliveira <markito@redhat.com>

Adding Red Hat to the list of contributors.

---

about/contributors.md

Signed-off-by: David Lyle <dklyle0@gmail.com>

Adding dklyle

---

roadmap.md

We're having trouble sticking to the roadmap. The hope behind this PR is that if the roadmap was easier to reference, as in "We're working toward section 0.1.3 right now; please hold off on other PRs" we'll stick to the roadmap.
Signed-off-by: Rachel Myers <rachelmyers@google.com>

Replace bullets with numbers

---

serialization.md
spec.md

use camelCase in our property names

---

Makefile
spec.md
tools/verify-docs.sh
tools/verify-specs.sh

Also added "Cloud Event" and "Cloud Events" to the list of banned phrases for our tooling - which should catch uses of the spaced version.
Closes #153

Cloud Events -> CloudEvents

---

GOVERNANCE.md
README.md

And added some docs for how to create a new release.

Add pointers in our README to our docs - released and master

---

spec.md

Signed-off-by: David Delabassée <david.delabassee@gmail.com>

fixed link typo

---

about/contributors.md

Signed-off-by: Yaron Haviv <yaronh@iguazio.com>

update iguazio contribs info

---

about/contributors.md

Signed-off-by: Klaus Deissner <klaus.deissner@sap.com>

Updated the list of SAP contributors

---

http-transport-binding.md

Make http header names case-insensitive

---

about/contributors.md

Signed-off-by: Mark Peek <markpeek@vmware.com>

Fix name copy/paste and update Dispatch project link

---

community/demos.md

Add page for our KubeCon 2018 EU demos

---

community/contributors.md

Signed-off-by: Ryan Zhang <y.zhang@alibaba-inc.com>

add Alibaba to the contributor list

---

community/demos.md

I'll wait a bit before merging, so if you want your repo added just add a comment to the PR, or drop me a message.

Add links to people's demo code

---

README.md

https://www.cncf.io/projects/website-guidelines/
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

Add reference to CNCF sandbox

---

spec.md

Closes #131 
ping @cathyhongzhang 

Pull 'data' out from under 'context attributes'

---

README.md

update pict URL

---

README.md

Signed-off-by: Stevo Slavic <sslavic@gmail.com>

Reference web hook spec draft in readme

---

tools/verify-links.sh

fix issue with filenames starting with http

---

community/open-source.md

Signed-off-by: Matthias Wessendorf <matzew@apache.org>

adding link to jcloudevents

---

README.md

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

Mailing list updated

---

README.md

readme stuff for email

---

README.md

add f2f info

---

about/references.md

Signed-off-by: Roberto Perelman <rperelma@adobe.com>

Add reference to Adobe I/O Events

---

community/open-source.md

Initial POC for CloudEvent routing 
Signed-off-by: Matthias Wessendorf <matzew@apache.org>

Adding Gateway POC

---

community/open-source.md

Signed-off-by: Glenn Block <glenn.block@gmail.com>

Adding Extend SDK

---

amqp-format.md

Fix bad href

---

community/open-source.md

Signed-off-by: Michael Payne <michael@sooper.org>

Add Gloo and Dispatch as open-source projects that support CloudEvents.

---

primer.md

Seems like a leftover from the draft document got through.

Remove leftover from the primer

---

community/open-source.md

Signed-off-by: Matt Magaldi <matt.magaldi@blackrock.com>

adding argo-events to open source

---

json-format.md
spec.json

This adds a JSONSchema validation document and some docs on how
to validate events in JSON.
Fix #272
Signed-off-by: David Brown <dmlb2000@gmail.com>

Add JSONSchema Validation

---

amqp-format.md
json-format.md
spec.md

Closes #167 
(Doug: added "Closes")

Renaming Object to Any for issue 167

---

README.md

- Update our description since we're not really new any more
- Add a note about when we became a sandbox project, and a ref to
the TOC minutes in which we were approved - mainly so there's a record
of it someplace.  I've been asked for this info before and it should be more
easily found.

Very minor tweaks to README

---

extensions/distributed-tracing.md

Fix bad hrefs due to w3c move

---

GOVERNANCE.md

Define our versioning scheme across our docs

---

README.md

Reference was missing from README
Signed-off-by: Day, Jem <jday@paypal.com>

Add MQTT transport binding reference

---

README.md

Add some newbie guidance

---

protobuf-format.md

Amend example code to reflect changes made to context attribute names
Signed-off-by: Day, Jem <jday@paypal.com>

Proto Example code corrections

---

spec.md

We never actually said if its 0.1 or v0.1 or something else.

Be explicit about what the specversion string is

---

http-transport-binding.md

Minor fix for the TOC in the http transport binding

---

GOVERNANCE.md

Add an announcement to our release process

---

primer.md

thanks to @nuhamind2 for noticing
Fixes #374 

remove duplicate paragraph

---

spec.json

Signed-off-by: Fabio José <fabiojose@gmail.com>

minLength for non-empty attributes, add schemaurl

---

primer.md

Just a small fix for a broken link in the document.
Signed-off-by: Rodolphe Marques <marques.rodolphe@gmail.com>

Fixed a broken link in the primer

---

spec.md

clarify what OPTIONAL means

---

CONTRIBUTING.md
GOVERNANCE.md
README.md
SDK.md
amqp-format.md
amqp-transport-binding.md
artwork/README.md
community/README.md
community/contributors.md
community/demos.md
community/open-source.md
documented-extensions.md
extensions/distributed-tracing.md
extensions/sampled-rate.md
extensions/sequence.md
http-transport-binding.md
http-webhook.md
json-format.md
mqtt-transport-binding.md
nats-transport-binding.md
primer.md
proprietary-specs.md
protobuf-format.md
roadmap.md
share/README.md
spec.json
spec.md

To get the output, I Ran the following: 
```bash
prettier --write --prose-wrap=always $(find . | grep '.md' | grep -v .github)`
```
Had to reformat `GOVERNANCE.md` a little, it was written with invalid markdown originally.

Ran https://prettier.io/ command on all markdown.

---

spec.md

Do some clean-up items for PR 406 that were missed

---

README.md
artwork/README.md

Fix bad hrefs for our images

---

spec.md

No semantic changes, just some re-ordering to make it easier to follow/read:
- created REQUIRED and OPTIONAL attributes sub-sections
- moved all attribtues into the appropriate sub-sections
- alphabetized the attributes in each section
I think this makes it easier for people implementing the spec to
1) find the attribute they're looking for since it's alphabetized now,
2) know which attributes they MUST support since they're all in one
section now

Order the attributes section

---

documented-extensions.md

Signed-off-by: Klaus Deissner <klaus.deissner@sap.com>

Added link to dataref.md in documented extensions

---

spec.json

Signed-off-by: Day, Jem <jday@paypal.com>

Add "Subject" context attribute definition

---

documented-extensions.md
nats-transport-binding.md
primer.md

Misc. typo fixes

---

primer.md

We can always recreate the section if someone has text they want to add.
Thank to @erikerikson for noticing
Closes: #448

Remove blank section

---

spec.md

Be clearer about "time"

---

spec.md

Closes #188
I think the rest of #188 is already addressed by our recent PRs around
uniqueness of IDs.
/cc @ljnelson

Add a little clarity around "type"

---

roadmap.md

Modify roadmap with a more clear goal of getting to v1.0

---

primer.md
spec.md

Who am I to question our AI overlords?
cc @n3wscott 

Fix some typos and grammatical errors per MS Word

---

json-format.md
primer.md

Addresses 1. and 3. from #414 
I've left out 2., because I think it has been clarified with #466

Clarifications on batching to address #414

---

spec.json

We no longer put extensions into an 'extensions' bag

---

primer.md

Closes #434
@n3wscott @cneijenhuis perhaps we could add some more text to this section to resolve https://github.com/cloudevents/spec/issues/414 ?

Add section to primer about error handling

---

README.md
SDK.md

Alphabetized the list of other docs too

add ptr to sdk doc

---

community/contributors.md

adding Scott Nichols to contributors.md
Signed-off-by: Scott Nichols <nicholss@google.com>

adding Scott Nichols to contributors.md

---

spec.md

fix double word

---

primer.md

Fix typo s/compliment/complement/

---

community/open-source.md

remove bad link for now

---

mqtt-protocol-binding.md
spec.md

fix minor typos

---

community/contributors.md

Signed-off-by: Neil Avery <neil@confluent.io>

adding contrib entry

---

kafka-protocol-binding.md

another try at clarifying kafka

---

README.md
adapters/aws-s3.md
adapters/github.md
adapters/gitlab.md
amqp-protocol-binding.md
avro-format.md
extensions/dataref.md
http-protocol-binding.md
http-webhook.md
json-format.md
kafka-protocol-binding.md
mqtt-protocol-binding.md
nats-protocol-binding.md
primer.md
roadmap.md
spec.avsc
spec.md

Please add your LGTM to this PR if you approve of v1.0
Eligible voters are:  Enterprise Holdings, Google, IBM, Microsoft, NATS/Synadia, PayPal, Platform9, Red Hat, RX-M, SAP, VMWare, Vlad Ionescu, Erik Erikson, John Mitchell

v1.0 release and vote

---

amqp-protocol-binding.md
avro-format.md
http-protocol-binding.md
http-webhook.md
json-format.md
kafka-protocol-binding.md
mqtt-protocol-binding.md
nats-protocol-binding.md
primer.md
spec.md

remove 'working draft' text

---

README.md

Fix README spec links

---

primer.md

Say it's ok to ignore non-MUST recommendations - at your own risk

---

GOVERNANCE.md

add rules for changing Admins

---

primer.md

To finally resolve #72 , I added a paragraph to the primer.

Paragraph about nested events to the primer

---

primer.md

Remove duplicated word "protocol".

Remove duplicated word

---

primer.md

Signed-off-by: Eric Bottard <ebottard@pivotal.io>

Fix formatting typo

---

community/contributors.md

add Tihomir

---

community/open-source.md

Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>

Adding Visual Studio Code extension to community open-source doc

---

SDK.md

Add some clarity around SDK milestones

---

Makefile
README.md

Add info about the new SDK mailing list

---

subscriptions-api-openapi.yaml
subscriptions-api.md

This will be updated with the bindings through next week

Draft for subscription API

---

discovery.md

Signed-off-by: Mike Helmick <helmick@google.com>

update discovery API with full REST paths and types.

---

SDK.md

Signed-off-by: Sergei Egorov <bsideup@gmail.com>

Replace "conical" with "canonical" in "SDK Requirements"

---

Makefile
discovery.md
subscriptions-api.md

And add the new specs to the checkers

Fix some hrefs and rfc2119 wording

---

adapters/aws-s3.md
adapters/couchdb.md
adapters/github.md
adapters/gitlab.md
amqp-protocol-binding.md
avro-format.md
discovery.md
extensions/dataref.md
extensions/distributed-tracing.md
http-protocol-binding.md
http-webhook.md
json-format.md
kafka-protocol-binding.md
mqtt-protocol-binding.md
nats-protocol-binding.md
primer.md
spec.avsc
spec.json
spec.md
subscriptions-api.md

name HEAD files as *wip

---

discovery.md

I don't think of this as a radical change to what's in there today, it's more of a naming changing for "producer". This is just a first step and a rough idea to get some discussions/brainstorming to happen.

Changes to data model

---

ds-primer.md

Direct copy from: https://gist.github.com/duglin/5920f706ee0ce608b0be1fa2e3669ce5
I took the liberty of includeing Klaus' sourcetemplate stuff since it
seems like people are ok with and I wanted to show what it would look like
when in use.

Draft of DS-Primer

---

schemaregistry/schemaregistry.yaml

Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Schema Registry - Change version to comply with OpenAPI spec

---

adapters/couchdb.md
extensions/dataref.md
spec.json
spec.md

Closes #654
- Uses past tense
- Update to match the github adapter doc
/cc @about-code

fix some types

---

.gitignore
spec.json

Bring 'datadef' definition into line with specification

---

README.md

add missing sdks to readme

---

ds-primer.md

So far the subscription and discovery effort was mostly discussed from the consumer perspective. I divided the use cases into use cases for consumers, intermediaries, and producers and added cases for intermediaries and producers.

Adding use cases for producers and intermediaries

---

discovery.md

[Discovery] loosen permissions requirement on resources (#680)

---

discovery.md
ds-primer.md

[Discovery] Add an ID field that can not change

---

http-protocol-binding.md
spec.md

Another attempt to fix https://github.com/cloudevents/spec/issues/645
See also https://github.com/cloudevents/spec/pull/660

Clarify difference between message mode and HTTP content mode

---

pagination.md

Just a first draft of a "pagination" spec. Rather than put it into Discovery, I thought that we might be able to define it once and reuse it for all of the specs.

First pass at pagination

---

README.md

Update zoom link with password

---

discovery.md

Signed-off-by: Remi Cattiau <remi@cattiau.com>
No explanation required I guess

chore: fix typo

---

json-format.md
spec.json

Fixes: https://github.com/cloudevents/spec/issues/702

Allow JSON values to be null, meaning unset.

---

community/contributors.md

My PR: https://github.com/cloudevents/spec/pull/412

Added Heng to contributors

---

community/open-source.md

new url for vmware dispatch

---

community/open-source.md

Adding:
- Knative Eventing
- VEBA
Removing:
- Dispatch

Add Knative Eventing, VEBA to open source links. Remove Dispatch.

---

community/GOVERNANCE.md
spec.md

Talk about how we'll use "rc" release version strings and how we'll never update the "minor" version number.

talk about rc releases

---

.github/workflows/verify.yaml
.travis.yml
README.md

try actions

---

Makefile
README.md
SDK.md
amqp-protocol-binding.md
community/SDK-GOVERNANCE.md
protobuf-format.md
websockets-protocol-binding.md

typos/cleanup in prep for v1.0.1

---

community/SDK-GOVERNANCE.md
tools/verify-links.sh

Just minor typos that @dazmua found in #737 that I missed.
See if sleeping help the curl in the tool.

Misc fixes to tool and @dazuma review

---

json-format.md
spec.md

addresses https://github.com/cloudevents/spec/issues/738
Signed-off-by: Christoph Schwaegerl <c.schwaegerl@sap.com>

clarified integer to optionally include a sign

---

community/GOVERNANCE.md

fix href checking

---

amqp-protocol-binding.md
avro-format.md
http-protocol-binding.md
http-webhook.md
json-format.md
kafka-protocol-binding.md
mqtt-protocol-binding.md
nats-protocol-binding.md
primer.md
roadmap.md
spec.md
websockets-protocol-binding.md

prep for post-v1.0.1

---

subscriptions-api.md

[subscriptions] clarify our various subscription properties

---

discovery.md

and
- removed some tabs
- re-ordered sample to align with order in which attributes are defined

add missing property

---

subscriptions-api.md

Changes based on our deep-dive sessions.
I decided to just jump to the more compact form of filters.

changes from deep dive

---

amqp-protocol-binding.md

Signed-off-by: Eric Bariaux <375613+ebariaux@users.noreply.github.com>

Fixed typo in AMQP binding

---

community/GOVERNANCE.md

Tweak process to allow typo fixes w/minimal process

---

expression-language.md

CloudEvents SQL Expression Language

---

discovery.md

Specify what it means if a Service isn't in the GET response

---

CESQLLexer.g4
CESQLParser.g4
expression-language.md

This PR includes the lexer and grammar specs to implement CESQL in the ANTLR4 format. 
It also includes some small fixes/typos I made to the spec found out while working on the grammar

[CESQL] Add ANTLR4 grammar

---

expression-language.md

Give more explanations on functions overloading, variadic, etc

[CESQL] Specify functions overloading

---

primer.md
spec.md

docs: Expand versioning suggestions in the Primer

---

expression-language.md

Add `ABS` function https://www.w3schools.com/sql/func_mysql_abs.asp

 [CESQL] Add ABS

---

cesql_tck/README.md
cesql_tck/binary_comparison_operators.yaml
cesql_tck/binary_logical_operators.yaml
cesql_tck/binary_math_operators.yaml
cesql_tck/case_sensitivity.yaml
cesql_tck/casting_functions.yaml
cesql_tck/context_attributes_access.yaml
cesql_tck/exists_expression.yaml
cesql_tck/in_expression.yaml
cesql_tck/integer_builtin_functions.yaml
cesql_tck/like_expression.yaml
cesql_tck/literals.yaml
cesql_tck/negate_operator.yaml
cesql_tck/not_operator.yaml
cesql_tck/parse_errors.yaml
cesql_tck/spec_examples.yaml
cesql_tck/string_builtin_functions.yaml
cesql_tck/sub_expression.yaml

I've extracted from the reference implementation I'm working on (https://github.com/cloudevents/sdk-java/pull/363) the test cases and I've built this TCK, testing all the basic features of the language (~200 test cases).
The README contains the details on how to use it.

[CESQL] TCK

---

subscriptions-api.md

fix some typos

---

http-protocol-binding.md

* fix: Clarify HTTP header value encoding and decoding requirements
Fixes #777
Once this is agreed, we should also document conformance tests, but
it's unclear at the moment where they should live.

Clarify HTTP header value encoding and decoding requirements (#793)

---

expression-language.md

Given I had recently some questions about error handling and how the evaluator should deal with them, I propose this clarification/change in the spec that explains how error handling works.
I've also implemented this concept in the reference implementation: https://github.com/cloudevents/sdk-java/pull/363/files#diff-e12dcb9b95420aee80084115f90835327d3e03a11153feb9a5915cefed4a0f67

[CESQL] Clarify error handling

---

kafka-protocol-binding.md

[Kafka spec] Remove the conflicting sentence

---

kafka-protocol-binding.md

Backport of https://github.com/cloudevents/spec/pull/813
(cherry picked from commit ca5bc522208e50a00a49b341d78a2b28bc58aa7e)

[1.0.1] Backport Remove the conflicting sentence

---

cesql_tck/like_expression.yaml

Added 2 test cases that I've found out to fail while testing the reference implementation in sdk-java

[CESQL] Expand like test cases

---

expression-language.md

[CESQL] Added suggestions sections with error handling

---

schemaregistry/schemaregistry.md
schemaregistry/schemaregistry.yaml

This update adds change notification and replication support to the schema registry.

schema registry replication

---

.github/pull-request-template.md
.github/workflows/release-notes.yaml

Fixes https://github.com/cloudevents/spec/issues/817
Signed-off-by: Scott Nichols <snichols@vmware.com>

Adding release note generator action based on k8s release notes generator tool

---

subscriptions-api-openapi.yaml

Per title, the #803 didn't included the OpenAPI change

[Subscriptions API] Fix OpenAPI as followup of #803

---

subscriptions-api-openapi.yaml
subscriptions-api.md

Added the `sql` filter dialect to subscriptions api filters.

[Subscriptions API] CESQL filter

---

http-webhook.md

Fix bad link

---

expression-language.md

- Fixed some typos, and grammar and punctuation mistakes.
- Changed some terms to a more familiar ones.

Language review of the cesql expression language

---

documented-extensions.md
extensions/sampledrate.md

Add missing property name

---

primer.md

Fixes #
Fixed a small typo.
- fix typo
-
-
```release-note
```

Fix small typo.

---

ce_discovery.yaml
discovery.md

Prepares for #699
- clean up the API specification
- remove duplication
- follow REST best practices
- use filters over collections
- avoid using query params to alter HTTP semantics
- synchronize OpenAPI declaration with Specification
```release-note
refactor(discovery)!: Clean API spec/sync OpenAPI doc
```

Clean API spec/sync OpenAPI doc

---

community/contributors.md

fix bad url

---

primer.md

Per our call last week - remove some company references.

remove some company references

---

community/contributors.md

Add Jon Skeet to contributor list

---

http-webhook.md

Fixed erroneous header name

---

http-webhook.md

Follow-up PR equivalent to errata merged into 1.0.1

Fix for issue 781

---

subscriptions-api.md

Fixes #
The filters example was not matching the latest changes

fix: filters subscription example

---

subscriptions-api-openapi.yaml
subscriptions-api.md

AI "PR for credential properties"

Sink credentials

---

README.md

add link to our channel

---

README.md
community/GOVERNANCE.md
community/SDK-PR-guidelines.md
community/SDK-maintainer-guidelines.md
discovery/discovery.yaml
discovery/spec.md
misc/roadmap.md

fix more links

---

README.md
community/GOVERNANCE.md
community/SDK-PR-guidelines.md
community/SDK-maintainer-guidelines.md
roadmap.md

fix links for v1.0.1

---

GOVERNANCE.md
README.md
roadmap.md

fix links for v1.0

---

discovery/spec.md

fix json and add clarity about what's required

---

README.md

Fix link to recordings

---

discovery/spec.md

Would be nice to know if POST/PUT are supported w/o "discovery by error".

Add support for "update" in GET /features

---

discovery/spec.md

Found some of the text hard to follow

Just some wordsmithing

---

discovery/spec.md

Be clear about rejecting requests with missing fields

---

discovery/spec.md

It seemed like the filtering stuff could use more clarity and MUSTs to ensure interop.

More filter constraints

---

discovery/discovery.yaml

@erikerikson wanna take a look? I don't know openapi so I'm not sure if this is correct

openapi changes for #928

---

README.md
cloudevents/SDK.md
cloudevents/translated/zh-cn/README_CN.md
cloudevents/translated/zh-cn/SDK_CN.md

just alphabetize things

---

discovery/spec.md

typo noticed by Erik

---

OWNERS
cloudevents/primer.md

add Klaus as an admin

---

misc/tools/verify-links.sh

remove old code

---

subscriptions/spec.md
subscriptions/subscriptions-openapi.yaml

I noticed the OpenAPI for subscription was never updated after the spec change a year ago.  Fixing that.
```release-note
updated the subscription OpenAPI to the latest defined by the subscription text.
```

Fix subscriptions OpenAPI

---

README.md
cloudevents/translated/zh-cn/README_CN.md

fix bad URLs

---

misc/RELEASE_NOTES.md
misc/tools/verify-links.sh

Signed-off-by: Doug Davis <duglin@gmail.com>

fix checker for macs

---

cloudevents/spec.md

Fix broken link introduced in previous PR merge.

Fix broken link reference

---

community/GOVERNANCE.md

The intention is that this covers the *content* changes required as part of #954.
(There may be other files I'm not aware of... happy to be educated and take another pass.)

Proposed governance changes from the branching discussions

---

README.md
cloudevents/working-drafts/xml-format.md
pagination/spec.md

add missing version strings

---

cloudevents/working-drafts/xml-format.md

This does not attempt to cover any of the controversial aspects of #972
and indeed there may be some uncontroversial aspects of #972 that
I haven't yet taken.)

Minor tweaks to the XML format

---

README.md

Deprecate v1.0 branch

---

README.md
roadmap.md

Deprecate v1.0.1 branch

---

README.md
misc/RELEASE_NOTES.md
misc/roadmap.md

Deprecate v1.0.2 branch

---

cloudevents/formats/json-format.md
cloudevents/primer.md
cloudevents/spec.md
cloudevents/working-drafts/xml-format.md

There may be some more work required to clarify the nature of
extension attributes.
Fixed a few typos I spotted as I went along.

Initial definition of "core" attributes

---

discovery/discovery.yaml
discovery/spec.md

Add a deprecated timestamp

---

cloudevents/languages/zh-CN/adapters/aws-s3.md

translate spec/cloudevents/languages/zh-CN/adapters/aws-s3.md to zh-cn
Signed-off-by: VedaGao <gymti2014@163.com>

translate spec/cloudevents/languages/zh-CN/adapters/aws-s3.md to zh-cn

---

docs/GOVERNANCE.md

Add a step to the review process to check extensions

---

cloudevents/formats/json-format.md

Be clear that data_base64 isn't a CE attribute

---

subscriptions/spec.md

just typos

---

cloudevents/spec.md

Add some reasons for why binary mode might be used

---

cloudevents/primer.md
cloudevents/spec.md

Add some clarity around nested CEs

---

cloudevents/languages/zh-CN/RELEASE_NOTES.md

Translate spec/cloudevents/languages/zh-CN/RELEASE_NOTES to zh-CN
#1027

Translate spec/cloudevents/languages/zh-CN/RELEASE_NOTES to zh-CN

---

tools/verify-links.sh

Allow bookmarks to be case insensitive

---

subscriptions/spec.md

fix: world spelling mistakes in subscription spec

---

cloudevents/http-webhook.md

Clarification for the abuse protection callback

---

cloudevents/bindings/amqp-protocol-binding.md
discovery/spec.md

Permit underscore character as alternate separator

---

discovery/spec.md

First pass at the next major rev of the discovery spec.
Tries to align with this: https://drive.google.com/file/d/1C8JrRPMlzwk9uBvHEaRVbfZU2orHmeGp/view

discovery draft v2

---

cloudevents/bindings/kafka-protocol-binding.md

(As discussed in previous meetings.)

Note around empty messages for Kafka

---

cloudevents/bindings/amqp-protocol-binding.md

(As discussed in yesterday's meeting.)
I've kept this brief as I don't feel it merits a huge amount of detail/motivation, but we can add more if folks think it beneficial.

Prohibit mix-and-match of AMQP separators

---

discovery/spec.md

Lots of changes:
- added the notion of "References" that can be inlined based on ?inline on the GET
- added `origin` property which points to the true owner of the resource
- add ?inline to queries
- lots of minor syntax changes, like created a common attribute section
- use maps in the queries instead of arrays for easy reference

Tweak how we deal with references

---

.clomonitor.yml

More CLOMonitor stuff

---

discovery/spec.md

Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

Fix typo specifation -> specification

---

discovery/spec.md

Basically what we presented during last week's call.

next round of discovery edits

---

discovery/README.md
discovery/languages/zh-CN/spec.md

fixes for the checker

---

discovery/spec.md

More edits based on our 10/18 call

---

discovery/spec.md

[Discovery] Fill in more info

---

discovery/spec.md

Add missing commas

---

README.md

Signed-off-by: Doug Davis <duglin@users.noreply.github.com>

Point to Trail of Bits website for security report too

---

README.md

Add OpenSSF Badge

---

docs/contributors.md

Signed-off-by: Jie Ding <jie.ding@linkall.com>
- add JieDing to the contributor list

Add JieDing to the contributor list

---

cloudevents/extensions/sampledrate.md

Clarity on who does event sampling (we don't mandate it)

---

languages/zh-CN/README.md
languages/zh-CN/translations.md

Regularly check and sync English spec to Chinese translation
- add badges to Chinese README
- update translation last edit time

Update Chinese readme

---

cloudevents/primer.md

Further debate welcome; there's a balance about how much we want to say here.
Closes #993.

Clarify status of documented extensions

---

registry/spec.md

Add some missing stuff to make it more real

Registry Service clean-up

---

cloudevents/extensions/dataref.md

Fixes #1136 
Well, part of 1136's discussion. The originator of #1136 hasn't replied to our queries so until they do we'll assume using dataref + this fix should be good enough.

Warn people about dataref

---

tools/test_verify.py
tools/verify.py

Fix tool - support "maybe" and ignore words that start with backtick

---

registry/spec.md

Based on @clemensv PoC work, this makes things more readable.

Rename Group to DefinitionGroup

---

registry/spec.md

- updating the `GET /endpoints/123` data sample on the spec
```release-note
```

Adding get for singular endpoint

---

registry/spec.md

Add ID (immutable) and Self to registry root

---

cloudevents/spec.md

Fixes #
-
-
-
```release-note
```

minor typo

---

registry/spec.md

- Added versionsUrl, versionsCount fields
- removed "type"
- s/URL/Url/ where appropriate
- "versions" in model MUST be >= 1 - meaning there will always be at least 1 version of a resource
- added missing fields in some samples
- wrap at 80 cols
- `id` must be case-insensitive unique since it can appear in case-insensitive locations, such as URLs or HTTP headers
Fixes: #1180

Add versionsXXX fields and other misc tweaks

---

README.md
cloudevents/SDK.md
cloudevents/languages/zh-CN/SDK.md
languages/zh-CN/README.md

add link to sdk support table

---

cloudevents/SDK.md

Fixes #1207 
- Update SDK support status for RocketMQ binding
N/A

Update SDK support status for RocketMQ binding

---

README.md
cloudevents/SDK.md

- mention the SDKs are (sort of) independent of the spec

more review changes

---

cloudevents/documented-extensions.md
cloudevents/extensions/dataref.md
cloudevents/extensions/sampledrate.md

Add missing ext & make at least one attribute REQUIRED for each ext

---

cloudevents/spec.md

/cc @jskeet 
Just fixed some line wrapping too

Add some clarifying text about identifying attributes

---

cloudevents/extensions/authcontext.md
cloudevents/formats/protobuf-format.md
cloudevents/working-drafts/xml-format.md
tools/fake-docs/text-verification.md

Fixes #
-
-
-
```release-note
```

chore: fix some typos

---

cesql/spec.md

Fixes #1260 
- OR expressions MUST be short-circuit evaluated
```release-note
CESQL OR expressions are now required to be short-circuit evaluated
```

CESQL OR short-circuit evaluation

---

cesql/spec.md

Follow up on #1267 
- CESQL AND operations are short-circuit evaluated

CESQL AND operators are now short-circuit evaluated

---

subscriptions/spec.md

Typo: filter->filters

---

docs/open-source.md

Simulating CloudEvents with AsyncAPI and Microcks link added
Fixes #
-
-
-
```release-note
```

Update open-source.md: Add Microcks to open source projects list

---

README.md
cesql/README.md
cesql/languages/zh-CN/spec.md
cesql/spec.md
docs/RELEASES.md

Fixes some names on the new release

fixup some cesql names

---

cloudevents/formats/avro-format.md

fix typo in avro spec

---

cloudevents/extensions/bam.md

Fix typos in bam.md

---

docs/open-source.md

* Add `Cloud Shapes` as a product that use the CloudEvents spec
```release-note
Add `Cloud Shapes` as a product that use the CloudEvents spec
```

Add `Cloud Shapes` as a product that use the CloudEvents spec

---

subscriptions/spec.md
subscriptions/subscriptions-openapi.yaml

lowercase all attributes in subscription spec

---

tools/verify.py

x.com returns really really long headers now

fix ci issue

---

cloudevents/extensions/authcontext.md

wording tweak for issue 1251

---

tools/verify.py

ignore .github files

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue.md

Create a new issue template
